### PR TITLE
cleanup doxygen.h, update .gitignore

### PR DESCRIPTION
**Pull request by zchrissirhcz**
Hi, doxygen developers

This PR do some tiny cleanup, hope it can be useful for doxygen.

### CODE REVIEW

**Comment by albert-github** [comment]
How did you fine these redundant entries?

**Comment by zchrissirhcz** [comment]
I find them by using the CLion IDE. CLion use dark color to show them, and with mouse hovering on them will give hint that they are never used. BTW, I do double check by search each "never used xxx" in VSCode to ensure there is only one.

e.g.
image

**Comment by albert-github** [comment]
I don't get the image, which variables are not used?
I checked `varArgs` and `isPredefined` and they are both used.

**Comment by zchrissirhcz** [comment]
I found `varArgs` and `isPredefined` in `define.h` and `pre.l`. I think CLion is not smart enough to checking `pre.l` file (at least with default CLion settings).

**Comment by albert-github** [comment]
Well when I do a grep I see for `isPredefined`:
```
define.h:    bool isPredefined = FALSE;
pre.l:                                                 (!yyextra->expandOnlyPredef || def->isPredefined)
pre.l:                                          //     def ? def->isPredefined : -1
pre.l:                                              (!yyextra->expandOnlyPredef || def->isPredefined)
pre.l:                                              QCString result = def->isPredefined && !def->expandAsDefined ?
pre.l:                                              (!yyextra->expandOnlyPredef || def->isPredefined)
pre.l:                                            QCString result=def->isPredefined && !def->expandAsDefined ?
pre.l:                                              /*&& !def->isPredefined*/
pre.l:        if (yyextra->expandOnlyPredef && def && !def->isPredefined) def=nullptr;
pre.l:    def.isPredefined=TRUE;
pre.l:        def.isPredefined = TRUE;
pre.l:        def.isPredefined = TRUE;

```
and for varArgs:
```
define.h:    bool varArgs = FALSE;
pre.l:    while (!done && (argCount<def->nargs || def->varArgs) &&
pre.l:        if (c==',' && argCount==def->nargs-1 && def->varArgs)
pre.l:      (argCount>=def->nargs-1 && def->varArgs)) // variadic macro with at least as many
pre.l:  def.varArgs    = state->defVarArgs;
pre.l:        def.varArgs      = hasVarArgs;
pre.l:        //  qPrint(def.name),qPrint(def.definition),def.nargs,def.varArgs);
```

so they are definitely used.
I suspect that the used "tooltip" does not take the `.l` files into consideration.

**Comment by zchrissirhcz** [comment]
Actually the `pre.l` file generated `pre.cpp` in `${build_directory}/generated_src/pre.cpp`.

By enabling `CMAKE_EXPORT_COMPILE_COMMANDS` for doxygen's CMake build, the generated `compile_commands.json` file describes it:
```json
{
  "directory": "/home/zz/work/github/doxygen/cmake-build-debug/src",
  "command": "/usr/bin/c++ -DENABLE_TRACING=1 -DYY_BUF_SIZE=262144 -DYY_READ_BUF_SIZE=262144 -I/home/zz/work/github/doxygen/deps/TinyDeflate -I/home/zz/work/github/doxygen/deps/filesystem -I/home/zz/work/github/doxygen/deps/libmd5 -I/home/zz/work/github/doxygen/deps/liblodepng -I/home/zz/work/github/doxygen/deps/libmscgen -I/home/zz/work/github/doxygen/libversion -I/home/zz/work/github/doxygen/libxml -I/home/zz/work/github/doxygen/vhdlparser -I/home/zz/work/github/doxygen/src -I/home/zz/work/github/doxygen/deps/spdlog/include -I/home/zz/work/github/doxygen/cmake-build-debug/generated_src -g -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wdouble-promotion -Wformat=2 -Wno-unused-parameter -Wno-sign-conversion -Wno-format-nonliteral -Wno-implicit-fallthrough -std=gnu++17 -o CMakeFiles/doxymain.dir/__/generated_src/pre.cpp.o -c /home/zz/work/github/doxygen/cmake-build-debug/generated_src/pre.cpp",
  "file": "/home/zz/work/github/doxygen/cmake-build-debug/generated_src/pre.cpp"
},
```

I think CLion does not use `pre.cpp` into consideration, neither. Now I report it as an false positive in <https://youtrack.jetbrains.com/issue/CPP-33528/False-positive-for-Field-xxx-is-never-used-when-xxx-is-used-by-flex-generated-c> . Hope further CLion updates can fix it.

**Pull request merged**
