### PR TITLE
fix error file path with non-ansi code

### PR DESCRIPTION
**Pull request by Jiangshan00001**
fix this error:

https://github.com/doxygen/doxygen/issues/1166

### CODE REVIEW

**Comment by doxygen** [comment]
@Jiangshan00001 can you squash all your commits into a single one? Makes it easier to review and all commits belong to the same issue anyway.

**Comment by doxygen** [comment]
@Jiangshan00001 I've decide to implement this in a bit different/cleaner way. Since you didn't squash your commits, I couldn't really use this pull request, and decided to push my own [commit](https://github.com/doxygen/doxygen/commit/e002e293d9dc956a0634b3a4bcc8d93e655582d5).

**Comment by Jiangshan00001** [comment]
@doxygen fine.
i have not figured out how to squash the commits...

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.6.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Pull request closed without merging**
