### PR TITLE
issue #9719 \ref command does not insert title of referenced page

### PR DESCRIPTION
**Pull request by albert-github**
Adding the `title` as optional text as option to the `\anchor` command.

### CODE REVIEW

**Comment by albert-github** [comment]
Investigating ...

**Comment by albert-github** [comment]
Found solution.

**Comment by doxygen** [comment]
@albert-github In this case, I found it better to introduce an internal `@ianchor` command, as the title is only really needed internally.

**Comment by albert-github** [comment]
I didn't choose for the `\anchor` version as:
- I didn't see any risk in adding the option
- I think it might have advantages to have an anchor with a default text (so one can refer to it just with the anchor id and one doesn't have to provide the text every time one uses the anchor. Might be useful in case of multiple usages of parts that are no sections etc. but subparts of sections etc. that one wants to address).

**Pull request merged**
