### PR TITLE
Performance patches

### PR DESCRIPTION
**Pull request by thejh**
Hello!

I want to be able to run Doxygen on Linux kernel code parts, e.g. on all kernel code that is involved in the compilation of a specific device (determined using https://git.thejh.net/?p=cleanmysourcetree.git). In particular, I want big call/callee graphs (I'm testing with size limit 100 and no depth limit).

However, when I attempted that, it took pretty long. These patches reduce the required time on my system a lot.

I just re-ran my patched doxygen and the version of the master branch my patches are based on, built with "-ggdb -O3" (no LTO), with clean result directories to compare the times needed. Results:

patched:
```
$ time ~/gitty/3FOREIGN/doxygen/build/bin/doxygen
[...]
real	17m19.091s
user	64m6.501s
sys	1m3.239s
```

master:
```
$ date && sleep 1 && time ~/gitty/3FOREIGN/doxygen/build/bin/doxygen
Mi 30. Dez 21:22:03 CET 2015
[...]
Computing dependencies between directories... [last message visible at 21:51]
[around 21:54, it starts to generate call/callee graphs]
[at 22:23, after an hour, it's still generating call/callee graphs]
```

I'll tell you how long the master build took to complete when it's done. :D

Some of these changes are algorithmic and change the big-O complexity of the code, others are microoptimizations. If you don't want to merge some of the microoptimizations I did because they make the code look ugly, I can send a new pull request with just the important high-level stuff.

Note that two patches change the file naming scheme a bit and one requires a dot version that is from 2006 or newer if DOT_MULTI_TARGETS is turned on. Also, I have removed some of the logging calls to stdout, particularly the logging of all function names when generating call graphs.

### CODE REVIEW

**Comment by thejh** [comment]
Meh, I'll stop the run now. But it has run for four hours now and is still crawling through the call graph generation.

**Comment by doxygen** [comment]
I've been including some of the ideas suggested, but without using STL and typically solving them at a higher level. Can you have a look at the latest version from GitHub and see how it performs? and/or tell me in more detail which steps I have to do to reproduce the performance issues?

**Comment by t-b** [comment]
@thejh @doxygen 

I'm not sure exactly what tests the OP did but I tried to do some performance testing as well.

```
git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
cd linux
mkdir doc
cd doc
wget byte-physics.de/Downloads/Doxyfile
```

The whole kernel tree takes way too long, so I only used the include directory. Call and Caller graphs are also created.
The git checkout resides on a SSD, the doc folder was in a RAM disk.

My findings are:

doxygen --version
1.8.8 (debian jessie)
```
rm -rf html *tmp *db; time doxygen
real    8m26.567s
user    25m3.692s
sys     11m0.284s
```

doxygen trunk 7584c292, compiled in release mode with ` cmake -DCMAKE_BUILD_TYPE=Release` and gcc 4-8
```
rm -rf html *tmp *db; time doxygen

real    11m56.856s
user    25m17.848s
sys     19m2.500s
```

So for my tests trunk is slower than 1.8.8.

**Comment by doxygen** [comment]
@t-b Would be interesting to see the time summary you get at the end of a run when using the `-d time` option (and also set `QUIET` to `NO` in the config file) for both versions of doxygen. A small test I did on the 'include/net' directory only showed that git version is indeed slower but also produces almost 2x the number of dot graphs!

**Comment by t-b** [comment]
@doxygen 
doxygen 1.8.8
```
462.664 sec: Total elapsed time: 462.664 seconds
(of which 288.736 seconds waiting for external tools to finish)
----------------------
Spent 0.000 seconds in Searching for include files...
Spent 0.000 seconds in Searching for example files...
Spent 0.000 seconds in Searching for images...
Spent 0.000 seconds in Searching for dot files...
Spent 0.000 seconds in Searching for msc files...
Spent 0.000 seconds in Searching for dia files...
Spent 0.000 seconds in Searching for files to exclude
Spent 0.862 seconds in Searching for files to process...
Spent 5.190 seconds in Parsing files
Spent 0.108 seconds in Building group list...
Spent 0.161 seconds in Building directory list...
Spent 0.035 seconds in Building namespace list...
Spent 0.130 seconds in Building file list...
Spent 0.278 seconds in Building class list...
Spent 0.036 seconds in Associating documentation with classes...
Spent 0.062 seconds in Computing nesting relations for classes...
Spent 0.018 seconds in Building example list...
Spent 0.084 seconds in Searching for enumerations...
Spent 0.050 seconds in Searching for documented typedefs...
Spent 0.035 seconds in Searching for members imported via using declarations...
Spent 0.003 seconds in Searching for included using directives...
Spent 2.339 seconds in Searching for documented variables...
Spent 0.000 seconds in Building interface member list...
Spent 1.128 seconds in Building member list...
Spent 0.072 seconds in Searching for friends...
Spent 0.586 seconds in Searching for documented defines...
Spent 0.085 seconds in Computing class inheritance relations...
Spent 2.568 seconds in Computing class usage relations...
Spent 0.090 seconds in Flushing cached template relations that have become invalid...
Spent 0.001 seconds in Creating members for template instances...
Spent 0.239 seconds in Computing class relations...
Spent 0.080 seconds in Add enum values to enums...
Spent 0.597 seconds in Searching for member function documentation...
Spent 0.019 seconds in Building page list...
Spent 0.035 seconds in Search for main page...
Spent 0.017 seconds in Computing page relations...
Spent 0.018 seconds in Determining the scope of groups...
Spent 1.137 seconds in Sorting lists...
Spent 0.102 seconds in Determining which enums are documented
Spent 0.076 seconds in Computing member relations...
Spent 0.091 seconds in Building full member lists recursively...
Spent 0.047 seconds in Adding members to member groups.
Spent 0.246 seconds in Computing member references...
Spent 0.023 seconds in Inheriting documentation...
Spent 0.002 seconds in Generating disk names...
Spent 0.524 seconds in Adding source references...
Spent 0.284 seconds in Adding xrefitems...
Spent 0.099 seconds in Sorting member lists...
Spent 0.389 seconds in Computing dependencies between directories...
Spent 0.000 seconds in Generating citations page...
Spent 0.016 seconds in Counting data structures...
Spent 0.000 seconds in Resolving user defined references...
Spent 0.138 seconds in Finding anchors and sections in the documentation...
Spent 0.078 seconds in Transferring function references...
Spent 0.001 seconds in Combining using relations...
Spent 0.174 seconds in Adding members to index pages...
Spent 0.000 seconds in Generating style sheet...
Spent 5.832 seconds in Generating search indices...
Spent 0.000 seconds in Generating example documentation...
Spent 15.013 seconds in Generating file sources...
Spent 21.961 seconds in Generating file documentation...
Spent 0.010 seconds in Generating page documentation...
Spent 0.000 seconds in Generating group documentation...
Spent 16.252 seconds in Generating class documentation...
Spent 0.001 seconds in Generating namespace index...
Spent 0.001 seconds in Generating graph info page...
Spent 0.161 seconds in Generating directory documentation...
Spent 0.000 seconds in finalizing index lists...
Spent 78.969 seconds in Generating SQLITE3 output...
Spent 302.601 seconds in Running dot...
```

doxygen trunk
```
641.192 sec: Total elapsed time: 641.192 seconds
(of which 486.660 seconds waiting for external tools to finish)
----------------------
Spent 0.000 seconds in Searching for include files...
Spent 0.000 seconds in Searching for example files...
Spent 0.000 seconds in Searching for images...
Spent 0.000 seconds in Searching for dot files...
Spent 0.000 seconds in Searching for msc files...
Spent 0.000 seconds in Searching for dia files...
Spent 0.000 seconds in Searching for files to exclude
Spent 0.621 seconds in Searching INPUT for files to process...
Spent 4.850 seconds in Parsing files
Spent 0.106 seconds in Building group list...
Spent 0.028 seconds in Building directory list...
Spent 0.036 seconds in Building namespace list...
Spent 0.122 seconds in Building file list...
Spent 0.297 seconds in Building class list...
Spent 0.036 seconds in Associating documentation with classes...
Spent 0.062 seconds in Computing nesting relations for classes...
Spent 0.017 seconds in Building example list...
Spent 0.080 seconds in Searching for enumerations...
Spent 0.047 seconds in Searching for documented typedefs...
Spent 0.034 seconds in Searching for members imported via using declarations...
Spent 0.003 seconds in Searching for included using directives...
Spent 2.149 seconds in Searching for documented variables...
Spent 0.000 seconds in Building interface member list...
Spent 1.062 seconds in Building member list...
Spent 0.074 seconds in Searching for friends...
Spent 0.517 seconds in Searching for documented defines...
Spent 0.076 seconds in Computing class inheritance relations...
Spent 2.396 seconds in Computing class usage relations...
Spent 0.086 seconds in Flushing cached template relations that have become invalid...
Spent 0.217 seconds in Computing class relations...
Spent 0.082 seconds in Add enum values to enums...
Spent 0.526 seconds in Searching for member function documentation...
Spent 0.001 seconds in Creating members for template instances...
Spent 0.017 seconds in Building page list...
Spent 0.035 seconds in Search for main page...
Spent 0.017 seconds in Computing page relations...
Spent 0.018 seconds in Determining the scope of groups...
Spent 1.125 seconds in Sorting lists...
Spent 0.100 seconds in Determining which enums are documented
Spent 0.077 seconds in Computing member relations...
Spent 0.092 seconds in Building full member lists recursively...
Spent 0.047 seconds in Adding members to member groups.
Spent 0.211 seconds in Computing member references...
Spent 0.029 seconds in Inheriting documentation...
Spent 0.011 seconds in Generating disk names...
Spent 0.369 seconds in Adding source references...
Spent 0.208 seconds in Adding xrefitems...
Spent 0.111 seconds in Sorting member lists...
Spent 0.018 seconds in Computing dependencies between directories...
Spent 0.000 seconds in Generating citations page...
Spent 0.012 seconds in Counting data structures...
Spent 0.000 seconds in Resolving user defined references...
Spent 0.123 seconds in Finding anchors and sections in the documentation...
Spent 0.078 seconds in Transferring function references...
Spent 0.001 seconds in Combining using relations...
Spent 0.160 seconds in Adding members to index pages...
Spent 0.000 seconds in Generating style sheet...
Spent 4.115 seconds in Generating search indices...
Spent 0.000 seconds in Generating example documentation...
Spent 101.358 seconds in Generating file sources...
Spent 17.130 seconds in Generating file documentation...
Spent 0.009 seconds in Generating page documentation...
Spent 0.000 seconds in Generating group documentation...
Spent 11.116 seconds in Generating class documentation...
Spent 0.001 seconds in Generating namespace index...
Spent 0.001 seconds in Generating graph info page...
Spent 0.108 seconds in Generating directory documentation...
Spent 0.000 seconds in finalizing index lists...
Spent 0.000 seconds in writing tag file...
Spent 488.816 seconds in Running dot...
```

**Comment by groleo** [comment]
At some point I also did some perf analysis on doxygen.
Some of the things I noticed was that dot png might be replaced with in-browser dot renderer,
and also have a parallel caller-callee cross-references (which takes a lot of time).

**Comment by doxygen** [comment]
In the meantime the issues identified above have been (largely) implemented, but typically in a different way. So I think it is best to close this pull request. If you see further performance bottlenecks please let me know.

**Pull request closed without merging**
