### PR TITLE
GHC_NO_DIRENT_D_TYPE should be defined on Haiku

### PR DESCRIPTION
**Pull request by Begasus**
This also fixes detection for Haiku.

### CODE REVIEW

**Comment by albert-github** [comment]
Did you also report this bug upstream i.e. https://github.com/gulrak/filesystem as otherwise it will be lost when filesystem.hpp is updated?

**Comment by Begasus** [comment]
> 

Done now. :)

**Comment by Begasus** [comment]
Checked with a build for Grantlee, documents created successfully. :)

Doxygen-Grantlee

**Comment by gulrak** [comment]
I change the code with [filesystem #142](https://github.com/gulrak/filesystem/issues/142) (published with v1.5.12) to auto-detect the presence of a `d_type` field, that removed the need to define a macro for any new target system that doesn't have it.

Nevertheless thank you for the upstream notice!

**Comment by Begasus** [comment]
All that's needed is to update the file here to reflect the new one upstream? (can't find a sollution to set it to use a system version when packaging filesystem)

**Pull request merged**
