### PR TITLE
new addon doxyparse, a source parsing engine

### PR DESCRIPTION
**Pull request by joenio**
doxyparse parses source code and dumps the dependencies between the code
elements. Today doxyparse is in use by Analizo\* toolkit, a suite of
source code analysis tools, aimed at being language-independent and
extensible.
- http://analizo.org

Signed-off-by: Antonio Terceiro terceiro@softwarelivre.org
Signed-off-by: João M. Miranda joaomm88@gmail.com
Signed-off-by: Paulo Meirelles paulo@softwarelivre.org
Signed-off-by: Vinicius Daros vkdaros@mercurio.eclipse.ime.usp.br

It relates to the 2009 thread at:
- http://sourceforge.net/p/doxygen/mailman/message/23116871/

### CODE REVIEW

**Comment by joenio** [comment]
Hello guys, this is the second time I try to contribute with this addon, the first time was in 2009 but I got no response from doxygen community. If there is no intereset in accept this contribution I would like to know, this way I'll maintain the doxyparse tool as a project independent of doxygen. Thanks!

2009 mailing-list thread:

* http://sourceforge.net/p/doxygen/mailman/message/23116871/

**Comment by doxygen** [comment]
Hi Joenio,

I appreciate your contribution, but I'm not sure how people are supposed to be using the output of your tool. If it is just for info, or do you expect it to be used as input for further processing?

**Comment by joenio** [comment]
Hi dimitri,

I'm using the doxyparse output as input for another tool called Analizo (http://analizo.org), Analizo is a free, multi-language, extensible source code analysis and visualization toolkit. It supports the extraction and calculation of a fair number of source code metrics, generation of dependency graphs, and software evolution analysis.

Doxyparse is used as source-code static analysis tool, since its creation it has been used in some academic studies as you can see here: https://scholar.google.com.br/scholar?q=doxyparse

Doxyparse is today one of the well mature static analisys tool available on academic environment. And, also on the open source community. Answering this your question: "If it is just for info, or do you expect it to be used as input for further processing?" Yes, it is used as input for further processing.

Please, let me know if you have some idea of how can I improve this in order to be accepted.

Thanks!

**Comment by doxygen** [comment]
When the output needs to be processed by another tool, it is a good idea to use a format that is standardized and extendable. For instance XML, YAML, or JSON. Just plain text is very fragile and error prone to parse and extend and with a standardized format you typically get the parser for free.

Is it possible for you to change both doxyparse and Analizo such that a more robust data exchange file format is used?

**Comment by joenio** [comment]
Yes, of course, I'm going to use YAML. But, before, I'll take a look in specific formats like the GXL.

* https://en.wikipedia.org/wiki/GXL

**Comment by joenio** [comment]
Hi @doxygen, I made the conversion of the output to the YAML format, can you check if is ok?

**Comment by joenio** [comment]
Hi dimitri, you checked it? Thanks!

**Comment by doxygen** [comment]
Sorry for the delay. I'll look into it soon and thanks for the reminder.

**Comment by joenio** [comment]
ping

**Pull request merged**
