### PR TITLE
Added check for right angle bracket in case greater than used in specialization condition

### PR DESCRIPTION
**Pull request by JaredAll**

### CODE REVIEW

**Comment by albert-github** [comment]
The handling of `<` and `>` is a very delicate in template specializations, also in respect to `<=`  /  `>=` but also in respect to using spaces (when I'm not wistaken the C++ standard writes something about this and also there have been changes between the different versions of the standard).

Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem you try to solve with this proposed patch?  Please don't add external links as they might not be persistent.

**Comment by JaredAll** [comment]
Of course. This is attempting to solve the issue as described [here](https://github.com/doxygen/doxygen/issues/7727); this example is the same as the one in that issue.
[doxybug.tar.gz](https://github.com/doxygen/doxygen/files/4677118/doxybug.tar.gz)

**Comment by doxygen** [comment]
@JaredAll I think I found a more generic fix (https://github.com/doxygen/doxygen/commit/aa89f8773a50887ad20fbf683ff3c9af38c8fc5e). Can you test if it solves your problem as well?

**Comment by JaredAll** [comment]
@doxygen, looks like that fix takes care of it

**Pull request closed without merging**
