### PR TITLE
issue #8256 Possible to get enum values in the Enumeration Type documentation

### PR DESCRIPTION
**Pull request by albert-github**
Create to possibility to show also the initial values of the enumerators, when explicitly specified and the initializers have not been disabled by means of the configuration  setting MAX_INITIALIZER_LINES.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5721297/example.tar.gz)

### CODE REVIEW

**Comment by albert-github** [comment]
Instead of steering the showing of the enum values by mean is the `MAX_INIT_LINES` it is now, more flexible,  steered by the setting `SHOW_ENUM_VALUES` and the commands `\showenumvalues` and `\hideenumvalues`.

**Comment by Nulllix** [comment]
@albert-github Can you fix your changes so that this pull request will be completed?

**Comment by albert-github** [comment]
@Nulllix What do you mean with:
>Can you fix your changes so that this pull request will be completed?

1. Resolve conflicts, should be possible
2. SonarCloud problems. SonarCloud looked like very promising and most likely is but it gave also quite a few false positives and was quite intrusive (even when no new problems were found a comment was posted with the pull request and thus emails were sent out). Based on this and the lack of time to deeply dive into all the possible configuration possibilities it was decided to disable and remove it for doxygen.

**Comment by Nulllix** [comment]
@albert-github I was talking about SonarCloud. So... I just really like the idea of ​​​​adding values ​​for Enumeration Type, and I would like these changes to end up in the master branch so that I could use them myself.

I understand correctly that these changes are not yet in the original Doxigen repository?

**Comment by bradlitterell** [comment]
Nice, thanks!

**Comment by Nulllix** [comment]
Thanks, @albert-github! You are my hero!)

**Pull request merged**
