### PR TITLE
Building doxygen pdf documentation under Windows

### PR DESCRIPTION
**Pull request by albert-github**
Under windows the file make.bat is used to create the documentation.
Also an adjusted make.bat is needed as not the default refman is used but doxygen_manual

### CODE REVIEW

**Comment by groleo** [comment]
I think  /doc should be a cmake project() and all CMAKE_SOURCE_DIR in doc/CMakeLists.txt replaced with PROJECT_SOURCE_DIR. This means docs will be buildable w/o building main doxygen.
So make won't be needed either.
I'll try to turn the make.bat into a cmake target.

**Comment by albert-github** [comment]
Thanks for taking this task.

**Comment by groleo** [comment]
Please see master branch of https://github.com/groleo/doxygen/
steps to build it:

  cd doc
  mkdir build
  cd build
  cmake -Dbuild_doc=yes ../
  make docs

**Comment by albert-github** [comment]
Generation of pdf has been solved in other pull requests.

**Pull request closed without merging**
