### PR TITLE
Adding protection protected for Python

### PR DESCRIPTION
**Pull request by TreeN0de**
Adding conditions to differ between private and protected in python.

### CODE REVIEW

**Comment by albert-github** [comment]
Relevant in relation to this proposed pull request might be:  #7764, #6555 and #7759.

**Comment by TreeN0de** [comment]
Could someone please start the checks for me? This was my first merge request and I do not have the necessary permissions to start it myself.

**Comment by albert-github** [comment]
The failing checks are caused by the fact that MiKTeX doesn't work properly, in the mean time we replaced it with tlmgr.

**Comment by albert-github** [comment]
I was looking at the proposed pull request #6555 ad saw there that the functions with names starting and ending with a double underscore were classified as `public`, now they are `private`, An example is `__init__`, so is `__init__` a `public` or a `private` member of a class?

**Comment by TreeN0de** [comment]
Functions in python starting with `__` and ending  with `__` are special functions of every object in python. This functions can be accessed indirect. For example `__init__` is called when an new instance of an object is created. As I don‘t known of an ohter way to define a constructor in Python, I would declare this functions as public.
I thought, that I didnt' touched the spezific section (line in 1568  pyscanner.l)

**Pull request merged**
