### PR TITLE
issue #10447 Add explicit links to static pages

### PR DESCRIPTION
**Pull request by albert-github**
Add a new file with dummy links to all html / xhtml output files and add a dummy link on the index page to this new file.

### CODE REVIEW

**Comment by ilg-ul** [comment]
From the source code I see you add an empty anchor to a file `doxygen_crawl`, probably at the end of the home page, but I'm not able to understand how you generate the content. 

Are you sure that references to all pages referred via dynamically scripts are generated (a good example is `pages.html`, possibly all in the top bar).

Did you validate the resulting site, for example with <https://validator.w3.org/checklink>?

Another _classical_ tool that can be used to check broken links is <https://www.npmjs.com/package/broken-link-checker>.

**Comment by ilg-ul** [comment]
Could you post here the content of this extra file?

**Comment by albert-github** [comment]
The generation of the `doxygen_crawl` file is done by means of the, adjusted, call `Doxygen::indexList->addIndex<Sitemap>(generateSitemap);` in `doxygen.cpp`, the reference is generated in `index.cpp` and the content of the `doxygen_crawl` file is, automatically, generated in `sitemap.cpp`.

The content of the `doxygen_crawl.html` file for the project as given with #10447:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
<title>Validator / crawler helper</title>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.10.0"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
</head>
<body>
    <a href="xyz.html"/>
    <a href="index.html"/>
    <a href="doxygen_crawl.html"/>
    <a href="pages.html"/>
</body>
</html>
```

So the file `pages.html` is present.

**Comment by ilg-ul** [comment]
Did you check if the empty anchor elements are legal, according to the www standards?

**Comment by albert-github** [comment]
> Did you check if the empty anchor elements are legal, according to the www standards?

According to my knowledge and tests they are valid or do you have other information?

**Comment by ilg-ul** [comment]
Web technologies are not my thing, thus I would check the standards, they must be available somewhere.

**Comment by ilg-ul** [comment]
Just to double check, for my site I enabled the sitemap.xml and disabled the empty anchors hack. The w3.org validator did not parse the custom pages, so the hack seems necessary.

**Comment by ilg-ul** [comment]
Any idea why the macOS test failed?

**Comment by albert-github** [comment]
A temporary fix (looks like some interaction between libxml2 and the used Python version) has now been made so future updates of the doxygen code regarding the MacOS tests should be OK again.

**Comment by ilg-ul** [comment]
So, is this PR ready to merge?

**Pull request merged**
