### PR TITLE
issue #8390 Reusing documentation snippets

### PR DESCRIPTION
**Pull request by albert-github**
When `MARKDOWN_SUPPORT` is enabled run the documentation of the included file / snippet through the markdown processor (analogous to comment blocks in the different scanners).

### CODE REVIEW

**Comment by JPenuchot** [comment]
Hi @albert-github, I've been testing your feature and it looks like content that follows the beginning of a title won't display. Here's an example:

If you `\include{doc} foo.md` with `foo.md` containing the following:

```md
1. This will show up properly
1. This will show up properly
1. This will show up properly
1. This will show up properly

This will *show up* properly

> This will show up properly

This will show up properly

# This title won't show up

This won't show up either
```

Nothing will show up in the documentation starting from the title. I tried different title levels and got the same result.

**Comment by albert-github** [comment]
It might be one of the exceptions as (not mentioned explicitly) in the doxumentation:
> Some commands like \cond and \if don't work with this command due to the moment of parsing.
The included documentation should not have comment signs in it as they will appear in the documentation as
well.

But still best to create an issue for it.

**Comment by albert-github** [comment]
I thought I had seen another issue as well and looks like I found it now: #7062 best is to add your example to that issue.

**Comment by JPenuchot** [comment]
On 4/8/21 12:14 PM, albert-github wrote:
> I thought I had seen another issue as well and looks like I found it 
> now: #7062 <https://github.com/doxygen/doxygen/issues/7062> best is to 
> add your example to that issue.

Are you sure it's relevant to this issue? It points the lack of Markdown 
parsing in Doxygen 1.18.15 which was fixed, not the lack of Doxygen 
command parsing after the translation. I might be wrong but they seem to 
be separate issues to me.

Thanks for the Markdown fix however, I know someone will find that 
feature to be a total game changer. :)

**Comment by albert-github** [comment]
The problem in the mentioned #7062 indeed looks like it signals the only the problem of the non markdown processing, but when applying that fix we miss the entire 2nd table (i.e. the table through the `\includedoc`) so the issue #7062 is only partly solved.

**Pull request merged**
