### PR TITLE
issue #10917 Doxywizard in proposed patches doesn't run

### PR DESCRIPTION
**Pull request by albert-github**
Adding static linking option so the doxywizard might start.

### CODE REVIEW

**Comment by albert-github** [comment]
Does not yet work ...

**Comment by doxygen** [comment]
@albert-github The problem is that the [qt github action](https://github.com/jurplel/install-qt-action) used to install qt uses the [normal installer](https://ddalcino.github.io/aqt-list-server/) which installs a dynamically linked executables.

Probably it will work if you (as a user) first do these steps that are done by the github action as well:
```
curl -O https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe
./qt-unified-windows-x64-online.exe \
  --accept-licenses \
  --default-answer \
  --confirm-command install \
  qt.qt5.5152.win64_msvc2019_64
```

**Comment by albert-github** [comment]
I don't get the line:
> Probably it will work if you (as a user) first do these steps that are done by the github action as well

Do you mean:
- that before I can locally use executable with GitHub Actions I should run the menioned command?

or

It there a typo and on GitHub Actions this command should be added and where (before or after the qt action install)?

**Comment by doxygen** [comment]
> I don't get the line:
> 
> > Probably it will work if you (as a user) first do these steps that are done by the github action as well
> 
> Do you mean:
> 
>   * that before I can locally use executable with GitHub Actions I should run the menioned command?
> 

This is what I meant.

**Comment by albert-github** [comment]
Pity that there is no direct way to solve the issue on GitHub Actions as now individual users have to install Qt (which might interfere with their other installations of Qt).

**Comment by doxygen** [comment]
@albert-github Pity indeed. That's why I use a statically built version of Qt for the official release. One workaround may be to bundle the Qt DDLs together with the doxywizard binary. The dynamic loader will look for DLLs in the same directory as the executable first, I believe. The [dependencies](https://github.com/lucasg/Dependencies) tool can be used to test which libraries an executable uses.

**Comment by albert-github** [comment]
> I'm going to give the unified executable a try

Looks like I already had a Qt 5.15.2  installation lying around (from 2021?) and when adding the bin directory of this to the PATH everything was working.

**Pull request closed without merging**
