### PR TITLE
issue #10351 Search subpart research after a search

### PR DESCRIPTION
**Pull request by albert-github**
Implemented cookie that stores the selected category

### CODE REVIEW

**Comment by doxygen** [comment]
@albert-github I added [this commit](https://github.com/doxygen/doxygen/commit/390499d40f8cb9ea1e3440a30f33c77ead85e7db) so that the name is stored in the cookie and not the id. Indices may change (for instance if project didn't have a namespace and then one is added, all indices after the namespace in the list shift by 1).

**Comment by albert-github** [comment]
Makes sense, though in case the name doesn't exist anymore and the value 0 (i.e. All) is used wouldn't it make sense to write this value back into the cookie?

**Comment by doxygen** [comment]
I think this also happens. When the name stored in the cookie isn't found, 0 is returned, and selected. This should correspond to the 'All' item, which is written to the cookie unconditionally as part of the selection.

**Comment by albert-github** [comment]
Indeed I was thinking about the setting at the end of the search.js but here, through small layer of functions, the writeSettings is called.

**Pull request merged**
