### PR TITLE
Testing to find where perl disappears in appveyor

### PR DESCRIPTION
**Pull request by albert-github**

### CODE REVIEW

**Comment by albert-github** [comment]
Looks like I have to dive into the perl script to see where the problem lies ...

**Comment by albert-github** [comment]
I have the impression that the executables like `bibtex` got missing around November 26, 2016. No idea yet how to get them properly so I created a question:
https://tex.stackexchange.com/questions/524088/installing-miktex-missing-executables-when-using-miktexsetup

I'll leave this pull request open for a few days to see whether I get an answer and otherwise I'll make an issue from it.

**Comment by albert-github** [comment]
See also: https://github.com/MiKTeX/miktex/issues/443

**Comment by albert-github** [comment]
Looks like just copying the bibtex executable is not sufficient, must be some dll (as far as I can locally see all dlls are present) or other console message but nothing shown in log file probably just in a pop-up window  ...

**Comment by albert-github** [comment]
Problem has been fixed by means of upstream fix: https://github.com/MiKTeX/miktex/issues/443

**Comment by doxygen** [comment]
👍 Thanks for chasing this!

**Pull request closed without merging**
