### PR TITLE
Add support for Slice

### PR DESCRIPTION
**Pull request by externl**
This PR adds support for the [Slice language](https://doc.zeroc.com/ice/3.7/the-slice-language). 
* Support for `*.ice` files as a recognized file type.
* Add `OPTIMIZE_OUTPUT_SLICE` tag. 

We currently use our branch to generate documentation for [Ice](https://github.com/zeroc-ice/ice) located at https://doc.zeroc.com/api/ice/3.7/slice/

### CODE REVIEW

**Comment by albert-github** [comment]
I had a quick look and  I saw was the usage of the translator part.
I think the new functions should be added to the `TranslatorAdapter_1_8_15` and when possible the translations should be added for the different languages. The english version should not be placed in the different translators by default (unless there is no translation of the term possible, but this is up to the translator).

**Comment by albert-github** [comment]
Seen the compilation errors: In the mean time the definition of `SCOPEID` was removed from scanner.l as it was not used. In case it is needed again you have to reintroduce is.

**Comment by externl** [comment]
Thanks @albert-github. I made the fixes you suggested.

- Removed all of the english translations and added the default impl to `TranslatorAdapter_1_8_15`. My colleagues added proper Spanish and French translations.
- I replaced `SCOPEID` with `SCOPENAME`

**Comment by albert-github** [comment]
I'm not sure if it is a good idea, but I don't have a test set to check, to use `SCOPENAME` instead of `SCOPEID`, the definitions are different.

definitions:
`SCOPENAME "$"?(({ID}?{BN}*"::"{BN}*)*)(((~|!){BN}*)?{ID})`

`SCOPEID   {ID}({ID}*{BN}*"::"{BN}*)*({ID}?)`

**Comment by externl** [comment]
@albert-github I think that `SCOPENAME` is fine.

**Comment by externl** [comment]
@albert-github Fixed the various issues. Anything else necessary?

**Comment by albert-github** [comment]
I have to dive into it. A lot of changes are unfortunately just some space changes but give some perturbation / noise in the differences.
At first I saw a not transformed back translator file: src/translator_sr.h

**Comment by externl** [comment]
Thanks @albert-github. I've reset the translator files which we did not need to edit back to their original state.

**Comment by albert-github** [comment]
@externl, @bernardnormier, @pepone,
- As Slice code has been integrated it might also be a good idea to update the rest of the French and Spanish documentation. There are 9 other functions added to doxygen master (1.8.15):
    ```
    virtual QCString trCustomReference(const char * name)
    virtual QCString trDesignUnitHierarchy()
    virtual QCString trDesignUnitIndex()
    virtual QCString trDesignUnitList()
    virtual QCString trDesignUnitListDescription()
    virtual QCString trDesignUnitMembers()
    virtual QCString trDesignUnits()
    virtual QCString trFunctionAndProc()
    virtual QCString trVhdlType(uint64 type, bool single)
    ```
- does a, list of, translations of the Slice specific terms to other languages exist?

**Comment by externl** [comment]
@albert-github Thanks for merging! 

>As Slice code has been integrated it might also be a good idea to update the rest of the French and 
Spanish documentation. There are 9 other functions added to doxygen master (1.8.15): 
>```
>virtual QCString trCustomReference(const char * name)
>virtual QCString trDesignUnitHierarchy()
>virtual QCString trDesignUnitIndex()
>virtual QCString trDesignUnitList()
>virtual QCString trDesignUnitListDescription()
>virtual QCString trDesignUnitMembers()
>virtual QCString trDesignUnits()
>virtual QCString trFunctionAndProc()
>virtual QCString trVhdlType(uint64 type, bool single)
>```

We'll open a new PR with the language translations for the functions you listed.

> does a, list of, translations of the Slice specific terms to other languages exist?

Unfortunately there is no such list.

**Comment by albert-github** [comment]
@externl Thanks.

**Pull request merged**
