### PR TITLE
CI: Updates to Qt and Winflexbison

### PR DESCRIPTION
**Pull request by Croydon**
* I have created a winflexbison Conan recipe, so we can use this now to install winflexbison and don't need to do it "manual" anymore
  * Also updating winflexbison 2.5.15 -> 2.5.16
  * updating Qt for macOS from 5.11.1 to 5.11.3

### CODE REVIEW

**Comment by doxygen** [comment]
I see appveyor failed to build with:

```
win_bison: C:\Users\appveyor\.conan\data\winflexbison\2.5.16\bincrafters\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\bin\data/m4sugar/m4sugar.m4: cannot open: No such file or directory
```

so the bison build/install does not seen to be correct.

**Comment by Croydon** [comment]
The winflexbison recipe didn't copy correctly the `data` directory, so it's missing. A fix is in our CI pipeline, but may still take 12-24h until it's done, since some huge other recipes are scheduled before that. When it's done I will rebase this pull request to re-trigger the doxygen CI.

**Comment by Croydon** [comment]
Background: The upstream winflexbison project had the `data` directory and its content twice. The one path our Conan recipe copied it from got removed in the 2.5.16 release, but I forget to adapt our recipe in this regard, hence this error.

**Comment by Croydon** [comment]
Okay. AppVeyor is now fixed.

However, for some reason Travis started to fail. The very same build did succeed in my repository however...

https://travis-ci.org/doxygen/doxygen/builds/465508189

and also this build here did succeed as well 
https://travis-ci.org/doxygen/doxygen/builds/465511715

So no idea why the status check here says failing..

**Comment by albert-github** [comment]
I restarted the failing (mac) run and it passed now (probably a download glitch on travis).

**Pull request merged**
