### PR TITLE
Fortran interfaces improvements

### PR DESCRIPTION
**Pull request by melven**
Improve handling of Fortran interface/procedures (e.g. type definitions for function pointers / abstract interfaces).

### CODE REVIEW

**Comment by melven** [comment]
Draft because it depends on #9510

**Comment by melven** [comment]
#9510 was merged, so this is ready for review.

**Comment by doxygen** [comment]
@melven Can you please squash all individual commits together?

**Comment by melven** [comment]
> @melven Can you please squash all individual commits together?

Done.

**Pull request merged**
