### PR TITLE
remove vhdlparser/Makefile

### PR DESCRIPTION
**Pull request by makelinux**
because it is generated from vhdlparser/CMakeLists.txt

### CODE REVIEW

**Comment by albert-github** [comment]
I agree that this file could be removed.

Might be good to add the information:
```
#
# Generate parser (default target)
#
# when generating the parser with debug options it will look like:
#   make JAVACC_FLAGS=-debug_parser
#  or
#   make JAVACC_FLAGS="-debug_parser -debug_lookahead"
#
# Available debug options:
#  -debug_parser
#  -debug_token_manager
#  -debug_lookahead
#
# For other javacc settings / options consult the documentation of javacc.
```
in some way to the `CMakeLists.txt`

**Comment by makelinux** [comment]
> I agree that this file could be removed.
> 
> Might be good to add the information:
> 
> ```
> #
> # Generate parser (default target)
> #
> # when generating the parser with debug options it will look like:
> #   make JAVACC_FLAGS=-debug_parser
> #  or
> #   make JAVACC_FLAGS="-debug_parser -debug_lookahead"
> #
> # Available debug options:
> #  -debug_parser
> #  -debug_token_manager
> #  -debug_lookahead
> #
> # For other javacc settings / options consult the documentation of javacc.
> ```
> 
> in some way to the `CMakeLists.txt`
@albert-github, I've preserved the notice. Would you like to review?

**Comment by albert-github** [comment]
There is not a lot to review, looks OK to me information isn't lost now.

**Comment by makelinux** [comment]
> There is not a lot to review, looks OK to me information isn't lost now.

Who also need to approve and merge?

**Comment by albert-github** [comment]
By means of a proposed pull request all relevant persons are automatically informed.

**Pull request merged**
