### PR TITLE
xml: use STRIP_FROM_PATH on @file attributes.

### PR DESCRIPTION
**Pull request by groleo**

### CODE REVIEW

**Comment by zchrissirhcz** [comment]
I'm late here, suffering a document coverage generation failure, which I think it is due to this PR's modification (correct me if I'm wrong).
I don't understand why the `<location file=/some/path>` should be `<location file=/striped/path>`. Is there some examples that can help explain, the usage of `<location file=xxx>`, cause different result when with original path and stripped path?

@groleo @doxygen

**Comment by doxygen** [comment]
The idea of stripping parts of the path is to make the output more portable. So instead of e.g. `/home/dimitri/output/xml` which would only work on my system, one could have `output/xml`.

**Comment by zchrissirhcz** [comment]
Currently, I have a C++ project, under `rock` directory, with folder structures like the following:
```
.
├── examples
│   └── example.cpp
└── src
    ├── core
    │   └── rock
    │       ├── core.hpp
    │       ├── lapack.cpp
    │       ├── lapack.hpp
    │       ├── matrix.cpp
    │       └── matrix.hpp
    └── imgproc
        └── rock
            ├── filter.cpp
            ├── filter.hpp
            ├── imgproc.hpp
            ├── resize.cpp
            └── resize.hpp
```

I would like to generate documentation like this:
1. for all header files (matrix.hpp, lapack.hpp, filter.hpp, resize.hpp), the functions in these files show corresponding header file as `#include <rock/matrix.hpp>`, i.e. only with one directory as prefix, instead of directory names from project root, i.e. `#include <rock/core/rock/matrix.hpp>`. Thus, I would like to strip only `@CMAKE_SOURCE_DIR@/src/core` and `@CMAKE_SOURCE_DIR@/src/imgproc`.
2. I would like to generate both xml and html output files. Html files for user daily usage of the `rock` library, searching API usage. Xml files for generating document coverage report with tools such as coverxygen(https://github.com/psycofdj/coverxygen/), which depends on the xml file's `<location file=/path/to/file>` node and attribute.

So here comes my question, for the above example project, with speicfied `STRIP_FROM_PATH` striping  `@CMAKE_SOURCE_DIR@/src/core` and `@CMAKE_SOURCE_DIR@/src/imgproc`, the generated Xml files would be like:
```xml
<location file=rock/matrix.hpp>
<location file=rock/filter.hpp>
```
That is to say, now the Xml files does not contain full information of path and directory to get exactly where `matrix.hpp` and `filter.hpp` is. Yes, there is `@CMAKE_SOURCE_DIR@` available, but tools such as coverxygen can't determine if `matrix.hpp` is in `src/rock` or `src/imgproc` subdirectories, and that's what I think still required and should be stored in `<location file=>`.

To be clear, I would like the `file` attribute still keep subdirectory values from project root or the absolute path of current machine, but with `STRIP_FROM_PATH` works fine for generated html document correctly show short includings. Thus, I just made #8937 .
@doxygen

**Comment by zchrissirhcz** [comment]
I upload the mentioned example project to github, https://github.com/zchrissirhcz/rock .

Using the doxygen that build from my PR #8937, I pick one generated XML file:

```xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.3" xml:lang="en-US">
  <compounddef id="filter_8hpp" kind="file" language="C++">
    <compoundname>filter.hpp</compoundname>
      <sectiondef kind="func">
      <memberdef kind="function" id="group__imgproc_1gadc64bffc3550a9e3829ff206f9560dd8" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>void</type>
        <definition>void filter</definition>
        <argsstring>()</argsstring>
        <name>filter</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/zz/work/test/rock/src/imgproc/rock/filter.hpp" line="6" column="6" declfile="rock/filter.hpp" declline="6" declcolumn="6"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <programlisting>
<codeline lineno="1"><highlight class="preprocessor">#pragma<sp/>once</highlight><highlight class="normal"></highlight></codeline>
<codeline lineno="2"><highlight class="normal"></highlight></codeline>
<codeline lineno="5"><highlight class="normal"></highlight></codeline>
<codeline lineno="6" refid="group__imgproc_1gadc64bffc3550a9e3829ff206f9560dd8" refkind="member"><highlight class="normal"></highlight><highlight class="keywordtype">void</highlight><highlight class="normal"><sp/><ref refid="group__imgproc_1gadc64bffc3550a9e3829ff206f9560dd8" kindref="member">filter</ref>();</highlight></codeline>
<codeline lineno="7"><highlight class="normal"></highlight></codeline>
    </programlisting>
    <location file="/home/zz/work/test/rock/src/imgproc/rock/filter.hpp"/>
  </compounddef>
</doxygen>

```

As illustrated, now `declfile` and `file` are with different values:
```xml
<location file="/home/zz/work/test/rock/src/imgproc/rock/filter.hpp" line="6" column="6" declfile="rock/filter.hpp" declline="6" declcolumn="6"/>
```

But if with the original, the master branch of doxygen, the generated Xml file is:
```
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.2" xml:lang="en-US">
  <compounddef id="filter_8hpp" kind="file" language="C++">
    <compoundname>filter.hpp</compoundname>
      <sectiondef kind="func">
      <memberdef kind="function" id="group__imgproc_1gadc64bffc3550a9e3829ff206f9560dd8" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>void</type>
        <definition>void filter</definition>
        <argsstring>()</argsstring>
        <name>filter</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="rock/filter.hpp" line="6" column="6" declfile="rock/filter.hpp" declline="6" declcolumn="6"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <programlisting>
<codeline lineno="1"><highlight class="preprocessor">#pragma<sp/>once</highlight><highlight class="normal"></highlight></codeline>
<codeline lineno="2"><highlight class="normal"></highlight></codeline>
<codeline lineno="5"><highlight class="normal"></highlight></codeline>
<codeline lineno="6" refid="group__imgproc_1gadc64bffc3550a9e3829ff206f9560dd8" refkind="member"><highlight class="normal"></highlight><highlight class="keywordtype">void</highlight><highlight class="normal"><sp/><ref refid="group__imgproc_1gadc64bffc3550a9e3829ff206f9560dd8" kindref="member">filter</ref>();</highlight></codeline>
<codeline lineno="7"><highlight class="normal"></highlight></codeline>
    </programlisting>
    <location file="rock/filter.hpp"/>
  </compounddef>
</doxygen>
```
In which, the `declfile` and `file` are with same value:
```xml
<location file="rock/filter.hpp" line="6" column="6" declfile="rock/filter.hpp" declline="6" declcolumn="6"/>
```

**Comment by zchrissirhcz** [comment]
For my example project, the `file` and `declfile` are the same value, I don't know what their difference is.
I think using `file` for abosolute path and `declfile` for virtual path (i.e. the striped one) would be more clear.

**Pull request merged**
