### PR TITLE
When compound.xsd also compund.py changes

### PR DESCRIPTION
**Pull request by albert-github**
Regression on #8983
compund.xsd has changed so also compound.py should be updated.

### CODE REVIEW

**Comment by albert-github** [comment]
Mid air collision with update:
```
Commit: 00ac7043d3afeccb2f568b197dc629fe1f4561a0 [00ac704]
Date: Saturday, December 25, 2021 9:46:25 PM
Update of doxmlparser to include new qualifiedname tag
```

**Comment by doxygen** [comment]
@albert-github I think there is still something wrong with the build dependencies for these targets. Typically I see the regeneration only trigger when running make again after a successful build.

**Comment by albert-github** [comment]
@doxygen you mean that you only see a change of `compound.py` after the second build run? 
Strange, I just tried it again on an up to date repository, I changed `compound.xsd` and ran `nmake` on it and I see:
```
Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
Copyright (C) Microsoft Corporation.  All rights reserved.

-- GLOB mismatch!
-- The javacc executable: D:/mini_cygwin/bin/javacc.bat (found version "7.0.5")
-- The generateDS executable: D:/Programs/Python/Python37/Scripts/generateDS.exe (found version "2.37.15")
-- Configuring done
-- Generating done
-- Build files have been written to: ...
[  0%] Built target md5
[  2%] Built target lodepng
[ 13%] Built target mscgen
[ 13%] Checking the git repository for changes...
[ 13%] Built target check_git_repository
[ 13%] Checking the doxygen version for changes...
[ 13%] Built target check_doxygen_version
[ 15%] Built target doxygen_version
[ 17%] Built target xml
[ 17%] Built target generate_configvalues_header
[ 21%] Built target vhdlparser
[ 28%] Built target doxycfg
[ 28%] Generating .../generated_src/resources.cpp
Scanning dependencies of target doxymain
[ 28%] Building CXX object src/CMakeFiles/doxymain.dir/__/generated_src/resources.cpp.obj
resources.cpp
[ 28%] Linking CXX static library ..\lib\doxymain.lib
[ 95%] Built target doxymain
[ 95%] Linking CXX executable ..\bin\doxygen.exe
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
[ 95%] Built target doxygen
[ 95%] Updating compound.py from compound.xsd...
[ 95%] Updating doxmlparser module...
[ 97%] Built target update_doxmlparser_files
[ 97%] Linking CXX executable ..\..\bin\doxyparse.exe
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
[100%] Built target doxyparse
```

and on the second run:
```
Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[  0%] Built target md5
[  2%] Built target lodepng
[ 13%] Built target mscgen
[ 13%] Checking the git repository for changes...
[ 13%] Built target check_git_repository
[ 13%] Checking the doxygen version for changes...
[ 13%] Built target check_doxygen_version
[ 15%] Built target doxygen_version
[ 17%] Built target xml
[ 17%] Built target generate_configvalues_header
[ 21%] Built target vhdlparser
[ 28%] Built target doxycfg
[ 95%] Built target doxymain
[ 95%] Built target doxygen
[ 95%] Updating doxmlparser module...
[ 97%] Built target update_doxmlparser_files
[100%] Built target doxyparse
```

So this looks all OK to me.
(javacc I had to do some tricks on windows as I only have java and thus javacc on cygwin)

**Comment by doxygen** [comment]
It does not seem to be very reproducable, but I always run make before pushing the results to GitHub, so it should never be that the generated `compound.py` does not match the `compound.xsd`. And I've seen it happen a few times that it does get out of sync and I have to add another commit after it. Maybe it is because of switching between Git branches. I'll keep an eye on it.

**Pull request closed without merging**
