### PR TITLE
Allow function ptr with INLINE_SIMPLE_STRUCTS

### PR DESCRIPTION
**Pull request by Azq2**
image

### CODE REVIEW

**Comment by Azq2** [comment]
Alternative variant
image

```diff
diff --git a/src/memberdef.cpp b/src/memberdef.cpp
index c6f3cc76b..1f90af8f8 100644
--- a/src/memberdef.cpp
+++ b/src/memberdef.cpp
@@ -3889,7 +3889,7 @@ void MemberDefImpl::writeMemberDocSimple(OutputList &ol, const Definition *conta
     QCString ts = fieldType();
 
     if (isFunctionPtr())
-        ts = m_type + m_args;
+        ts = m_type + name() + m_args;
 
     if (cd) // cd points to an anonymous struct pointed to by this member
       // so we add a link to it from the type column.
```

**Comment by albert-github** [comment]
Can you please also post the original structure `GUI_METHODS`  from which the output is generated?

**Comment by Azq2** [comment]
> Can you please also post the original structure `GUI_METHODS` from which the output is generated?

```C
/**
 * GUI callbacks.
 * */
struct GUI_METHODS {
    void (*onRedraw)(GUI *);                                /**< Method for the drawing */
    void (*onCreate)(GUI *, malloc_func_t);                 /**< Constructor */
    void (*onClose)(GUI *, mfree_func_t);                   /**< Destructor */
    void (*onFocus)(GUI *, malloc_func_t, mfree_func_t);    /**< GUI is in focus */
    void (*onUnfocus)(GUI *, mfree_func_t);                 /**< GUI not in focus */
    int (*onKey)(GUI *, GUI_MSG *);                         /**< Keyboard handler */
    void *unk0;
    void (*onDestroy)(void *, mfree_func_t);                /**< Free resources */
    int (*method8)();
    int (*method9)();
    void *unk1;
};

```

**Comment by renesas-abigail** [comment]
@doxygen Is there any option to conditionally disable this feature? Ie to tell doxygen not to inline a specific struct, even if INLINE_SIMPLE_STRUCTS=YES?

If the function pointer name is long, the table is illegible (doesn't fit on the screen). For my project I want INLINE_SIMPLE_STRUCTS=YES for all structs that do not contain function pointers. For structs with function pointers I want the functions displayed as if INLINE_SIMPLE_STRUCTS=NO, more similar to regular functions. This was the behavior until 1.11.0, I am trying to update an older 1.8.x project to 1.14.0 and ran into this issue.

**Comment by doxygen** [comment]
@renesas-abigail Best to open a new issue for it, refer to this one, and include a self-contained example that shows the problem, then we can see how to best solve it.

**Pull request merged**
