### PR TITLE
Fortran type bound procedures

### PR DESCRIPTION
**Pull request by melven**
Add support for Fortran type bound procedures (class methods).

### CODE REVIEW

**Comment by melven** [comment]
Draft because it is based on #9510

**Comment by doxygen** [comment]
@melven Can you please squash all individual commits together?

**Comment by FranckReinquin** [comment]
I am eager to see this branch merged in the base branch ! We've been waiting for this feature for quite a long time now. Thanks a lot.

**Comment by FranckReinquin** [comment]
We've been using the branch version for several days now, and it works like a charm.
Without this functionnality, Doxygen is actually pretty useless with modern Fortran code. This should be considered a top priority for inclusion (but of course I am partial).

**Comment by doxygen** [comment]
@FranckReinquin Sorry it took a while, but the code has finally been integrated.

**Pull request merged**
