### PR TITLE
Use cstdint to define fixed width typeString

### PR DESCRIPTION
**Pull request by cmorty**
On some systems int64 wasn't 64 bit

### CODE REVIEW

**Comment by cmorty** [comment]
Ok, seems like this "Fix" actually broke something. I'll look into it.

**Comment by albert-github** [comment]
@cmorty,

You wrote:
> On some systems int64 wasn't 64 bit

"some" is a bit vague:
- any special systems in mind?
- what happened on these systems?

**Comment by cmorty** [comment]
Well, actually it was an extra-pedentic gcc that diverted me. My printf-checks (Coming in an upcoming PR) complained that `long unsinged int` (64 bit) isn't `long long unsigned int` (actually 64 bit, too).  
Yet the fact, that my changes broke something, hint at that there must actually be something wrong. I'll look into it.
I'll close this and report back, once I found out more....

**Comment by cmorty** [comment]
Sweet. It seems like I triggered a bug in qcstring. :)

**Comment by cmorty** [comment]
Nope, it's not qcstring, it's global initialisation: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-global-init

**Comment by cmorty** [comment]
Ok, forget this one. Setting
```
const bool FALSE = true;
const bool TRUE = false;
```
is just plain stupid..... *very, very embarrassed*

**Pull request closed without merging**
