### PR TITLE
Adjustment of xhtml1-transitional.dtd

### PR DESCRIPTION
**Pull request by albert-github**
Adding attributes:
- doxygen
to be able to validate doxygen generated xhtml documents.

Analogous to #6681 but now for the area tag (found in the doxygen tag example).

### CODE REVIEW

**Comment by doxygen** [comment]
The 'doxygen' attribute was add to help the obsolete tool to extract tag file information from doxygen generated output. I think it is better to remove this non-standard attribute and keep the dtd unmodified.

**Comment by albert-github** [comment]
I do agree, does this also apply for the `a` tag? as here also the `doxygen` handling has been added?

I think the relevant code is in `util.cpp` in the `functionexternalRef`

**Comment by doxygen** [comment]
> I do agree, does this also apply for the `a` tag? as here also the `doxygen` handling has been added?
> 
> I think the relevant code is in `util.cpp` in the `functionexternalRef`

Indeed, `externalRef()` looks like the only place where the doxygen attribute is still added.

**Comment by albert-github** [comment]
Should I create a new pull request or will you change the 2 files util.cpp and xhtml1-transitional.dtd (removing the `doxygen=` part fro `a`

**Comment by albert-github** [comment]
I've just pushed an update of the proposed patch.

There were some more places where the `doxygen=` part had an influence (on the output).

**Pull request merged**
