### PR TITLE
Latex output format fixes

### PR DESCRIPTION
**Pull request by BCiesla**
In this pull requests two issues related to LaTeX output are addressed
1. Align latex output to man format where each section name is terminated with colon.
2. Paragraph header in pdf has same indent as other sections like param or retval

### CODE REVIEW

**Comment by BCiesla** [comment]
Here's the key part of the example which shows the differences - left side is the output from 1.8.15, right is with the proposed changes. On the left sections "Errors" and "Restrictions" are not aligned with "See also" section. On the right section "See also" has added colon. Paragraphs Descriptions, Errors and Restrictions were created using @par command. Red line is added for reference.
comparison

I add also header file [API.h.txt](https://github.com/doxygen/doxygen/files/3406933/API.h.txt) and doxygen config [config.txt](https://github.com/doxygen/doxygen/files/3406932/config.txt) and whole pdf documents generated [with proposed changes](https://github.com/doxygen/doxygen/files/3406902/refman-1.8.15.pdf) and [without](https://github.com/doxygen/doxygen/files/3406901/refman-1.8.16.pdf).

**Comment by BCiesla** [comment]
**Regarding the `:`**
if the presence of : in the LaTeX / pdf is decided by the language  used in the document and it is intended (design decision) then I'm fine to drop this change. 

**Regarding doxygen.sty change**
I'm not able to build doxygen manual - tex says "! TeX capacity exceeded, sorry [main memory size=17000000].". I'm using texlive under Linux.
Are you using the same LaTeX distribution?

**Comment by albert-github** [comment]
I used on native windows:
`MiKTeX-pdfTeX 2.9.6839 (1.40.19) (MiKTeX 2.9.6840 64-bit)`
and under cygwin:
`pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/Cygwin)`

**Comment by albert-github** [comment]
**Regarding the `:`**
My intention here is to get the general rule of thumb what should be used, the problem with Docbook is definitely not good as here it is a mixture, a soon as the general definition is available I can update the relevant code,

@doxygen use everywhere `:` or nowhere or output format depending ?

**Comment by doxygen** [comment]
> @doxygen use everywhere `:` or nowhere or output format depending ?

@albert-github It should be consistent. If it is visually already clear that it is a heading, then the `:` should be omitted.

**Comment by albert-github** [comment]
I do agree that the colon should only be present when it is not clear that it is after a heading and that the usage should be consistent.

Using the example of this pull request, where user added for 'Description', 'Errors\' and 'Restrictions\` paragraphs with colon to the documentation and the 'Parameters', 'Returns\' and 'See also\' are generated by doxygen.

**HTML**

html

Here it is clear that the mentioned texts are headers and no colon necessary.

**LaTeX**

latex

Here it is clear that the mentioned texts are headers and no colon necessary.

**rtf**

rtf

Here it is clear that the mentioned texts are headers and no colon necessary and the colons should be removed.

**docbook**

docbook

Here it is clear that the mentioned texts are headers and no colon necessary and the colons that are present should be removed ('Returns\', 'See also').

**man**

man

Here it is clear that the mentioned texts are headers and no colon necessary and the colons that are present should be removed.

**Conclusions / Actions**

- HTML: Here it is clear that the mentioned texts are headers and no colon necessary, just quick visual check necessary to see whether it is done consistent.
- LaTeX: Here it is clear that the mentioned texts are headers and no colon necessary, just quick visual check necessary to see whether it is done consistent.
- rtf: Here it is clear that the mentioned texts are headers and no colon necessary and the colons should be removed.
- docbook: Here it is clear that the mentioned texts are headers and no colon necessary and the colons that are present should be removed.
- man: Here it is clear that the mentioned texts are headers and no colon necessary and the colons that are present should be removed.


@doxygen correct?

**Comment by doxygen** [comment]
@albert-github yes that looks correct to me

**Comment by albert-github** [comment]
OK I'll have a go at the coming week.

**Comment by albert-github** [comment]
Based on the above discussion I've just pushed a proposed patch, pull request #7146

**Pull request merged**
