### PR TITLE
Enable in page table of contents for LaTeX

### PR DESCRIPTION
**Pull request by albert-github**
currently the \\tableofcontents command is only supported for HTML.
In this patch:
- enable in page table of contents for LaTeX: \\tableofcontents['{'[option[:level]][,option[:level]]*'}']
     where option can be 'HTML',  'LaTeX' or 'XML'
- add the possibility to have maximum levels in the in page table of contents (possible per output type and per in page table of contents. Default is show all)

(side effect: possibility to have options with, nearly, all commands.)

### CODE REVIEW

**Comment by mosra** [comment]
In #625 I implemented emitting the `\tableofcontents` placeholder for the XML output, but without any "type" attribute, just an empty tag. 

Now, the `image` command is exported to XML like this:

```xml
<image type="html" name="image.png"></image>
```

Would you consider adding similar attribute (`types`?) to the XML `<tableofcontents/>` element as well to make it consistent with `<image>`? Thank you! :+1:

**Comment by albert-github** [comment]
I think this should be possible as well, the only thing is that it has to be defined how the XML-tags should look like, especially in the `xsd` file. As soon as I have a `xsd` definition I can have a look at the implementation.

**Comment by mosra** [comment]
One idea (`<tableofcontents>` having `<include type="html" />` children):

```patch
diff --git a/templates/xml/compound.xsd b/templates/xml/compound.xsd
index b4356acd..d00da253 100644
--- a/templates/xml/compound.xsd
+++ b/templates/xml/compound.xsd
@@ -29,7 +29,7 @@
       <xsd:element name="innergroup" type="refType" minOccurs="0" maxOccurs="unbounded" />
       <xsd:element name="templateparamlist" type="templateparamlistType" minOccurs="0" />
       <xsd:element name="sectiondef" type="sectiondefType" minOccurs="0" maxOccurs="unbounded" />
-      <xsd:element name="tableofcontents" minOccurs="0" maxOccurs="1" />
+      <xsd:element name="tableofcontents" type="tableofcontentsType" minOccurs="0" maxOccurs="1" />
       <xsd:element name="briefdescription" type="descriptionType" minOccurs="0" />
       <xsd:element name="detaileddescription" type="descriptionType" minOccurs="0" />
       <xsd:element name="inheritancegraph" type="graphType" minOccurs="0" />
@@ -120,6 +120,16 @@
     <xsd:attribute name="kind" type="DoxSectionKind" />
   </xsd:complexType>
 
+  <xsd:complexType name="tableofcontentsType">
+    <xsd:sequence>
+      <xsd:element name="include" type="tableofcontentsKindType" minOccurs="0" maxOccurs="unbounded" />
+    </xsd:sequence>
+  </xsd:complexType>
+
+  <xsd:complexType name="tableofcontentsKindType">
+      <xsd:attribute name="type" type="DoxOutputTypeKind" />
+  </xsd:complexType>
+
   <xsd:complexType name="memberdefType">
     <xsd:sequence>
       <xsd:element name="templateparamlist" type="templateparamlistType" minOccurs="0" />
@@ -547,7 +557,7 @@
 
   <xsd:complexType name="docImageType" mixed="true">
     <xsd:group ref="docTitleCmdGroup" minOccurs="0" maxOccurs="unbounded" />
-    <xsd:attribute name="type" type="DoxImageKind" /> 
+    <xsd:attribute name="type" type="DoxOutputTypeKind" />
     <xsd:attribute name="name" type="xsd:string" /> 
     <xsd:attribute name="width" type="xsd:string" /> 
     <xsd:attribute name="height" type="xsd:string" /> 
@@ -837,7 +847,7 @@
     </xsd:restriction>
   </xsd:simpleType>
 
-  <xsd:simpleType name="DoxImageKind">
+  <xsd:simpleType name="DoxOutputTypeKind">
     <xsd:restriction base="xsd:string">
       <xsd:enumeration value="html" />
       <xsd:enumeration value="latex" />
```

However, thinking more about this, I think it might be more flexible to have multiple `\tableofcontents` commands, each with just one "output type", like below:

```
\tableofcontents{html}
\tableofcontents{latex}
```

This could *later* (no, I'm *not* suggesting to implement this as part of this PR ;)) allow additional options for example to limit depth of the TOC box, differently for each output type, for example:

```cpp 
/* Include only one level of headers for HTML output but two in the LaTeX output */
\tableofcontents{html,1}
\tableofcontents{latex,2}
```

(In that case the XML would be just e.g. `<tableofcontents type="html"/ >`, no nested sequence of tags.)

**Comment by albert-github** [comment]
Thanks for the thoughts.

The already proposed extension of the implementation of the `\tableofcontents ` command is `\tableofcontents['{'[option][,option]*'}']` it is also to use multiple `\tableofcontents ` commands on a page (the the `\tableofcontents ` are concatenated). In this implementation the 'level' mechanism would be a bit harder to implement and I'm not sure if it would be nice from a consistency point of view, but it is an interesting thought.

I'll see what I can achieve with the suggested `xsd` change.

**Comment by albert-github** [comment]
Updated the pull request in respect to XML and also implemented the possibility for maximum levels shown in the in page table of contents.

**Comment by albert-github** [comment]
Restructuring is not a bad idea.
I  Have to check more thoroughly but I think the code in types.h:
```
    bool isHtmlEnabled()  const { return (m_mask & Html)!=0;  }
    bool isLatexEnabled() const { return (m_mask & Latex)!=0; }
    bool isXmlEnabled()   const { return (m_mask & Xml)!=0;   }
```
is not correct and should read:
```
    bool isHtmlEnabled()  const { return (m_mask & (1 << Html))!=0;  }
    bool isLatexEnabled() const { return (m_mask & (1 << Latex))!=0; }
    bool isXmlEnabled()   const { return (m_mask & (1 << Xml))!=0;   }
```

**Comment by albert-github** [comment]
Also in `commands.doc` is a small problem (not restructure problem, but one in the original patch) around line 2040 it reads:
> In case no \`option.

this has to be
> In case no \`option\`

**Comment by doxygen** [comment]
Indeed, see https://github.com/doxygen/doxygen/commit/b6c724e8ab5caeef1e3d065e4c2fa05740d87859 for the fixes

**Comment by doxygen** [comment]
and https://github.com/doxygen/doxygen/commit/ae25f5c41545e17b37d67ab7dabf422f0eb757aa for the documentation fix

**Comment by albert-github** [comment]
Looks OK now, except for the `.` after \`option\`

**Pull request merged**
