### PR TITLE
Bug 739680 - Using HTML entities in PROJECT_NAME

### PR DESCRIPTION
**Pull request by albert-github**
Implementation for LaTeX of special symbols by scanning string in case a & is found.

### CODE REVIEW

**Comment by albert-github** [comment]
In principle there is nothing against limiting the search part. Looking only for a-z and A-Z is insufficient, a number of entities contain numbers (e.g. sup2). An alternative would also be to limit the search to e.g. 10 chars.

**Comment by albert-github** [comment]
Would a construct like: 
  while (*q && *q != ';' && ((*q >= 'a' && *q <= 'z') || (*q >= 'A' && *q <= 'Z') || (*q >= '0' && *q <= '9')))
be better than the current proposed:
  while (*q && *q != ';')
Disadvantage of the new construct is we have to do some test for each character.
I can commit this without problems.

**Comment by doxygen** [comment]
Yes, I prefer the character check over the "process until ; or end of string" approach.

**Comment by albert-github** [comment]
Updated as suggested.

**Pull request merged**
