### PR TITLE
issue #7009 Python class diagram not created for the base class while works for the derived class

### PR DESCRIPTION
**Pull request by albert-github**
- handle imports with parenthesis
- improve handling of line continuation in `from ... import`

### CODE REVIEW

**Comment by doxygen** [comment]
@albert-github  I've pushed a slightly more elegant [solution](https://github.com/doxygen/doxygen/commit/7f0ea786de3153f535ca20280d6b8660ffefd2e6). Please check if that also addresses the problem.

**Comment by albert-github** [comment]
@doxygen, this does not address the issue as mentioned in #7009 (at the end the test case is attached)

I created 3 executables:
1. current master 7f0ea78
2. before the fix 04776ad
3. fix as proposed in this pul request applied on 04776ad (naming it `04776ad _7009`)

I looked at the image as shown in the file `classpy_d3_v_model_simple_1_1_d3_v_model_ctrl_simple.html` and here we see that the version of 1) and 3) are wrong, they show the grey box and 2) is correct.

**Image produced by 1)**

img_7f0ea78


**Image produced by 2)**

img_04776ad


**Image produced by 3)**

img_04776ad_7009


Other problems occur also with other pages, the case and the results: [test_case.tar.gz](https://github.com/doxygen/doxygen/files/3466987/test_case.tar.gz)

**Comment by doxygen** [comment]
Indeed, looks like I accidentally added a newline before the body of the scanner rule causing it to be ignored. Should be fixed with [this commit](https://github.com/doxygen/doxygen/commit/f554f9e4e4d06002e65aa49afc4560671348a42b)

**Comment by doxygen** [comment]
I do see a warning: 

`pyD3VModel.py...
/issue7009/tst/src/pyD3VModel.py:149: warning: Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 141)`

on both python files... probably a regression related to the earlier 'nested comments' counting change.

**Comment by albert-github** [comment]
Regarding the `Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 141)` ad the similar message from the other file, is strange all looks OK. Has to be investigated.

**Comment by albert-github** [comment]
As the original problem has been fixed, I'll close this pul request.
The problem regarding "Reached end" is a separate issue.

**Pull request closed without merging**
