### PR TITLE
A Lax is a Fish, and not a Cookie

### PR DESCRIPTION
**Pull request by ecxod**
Cookie “doxygen_width” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

### CODE REVIEW

**Comment by albert-github** [comment]
- What has the second change to do with the subject?
   -  When not related create a separate PR for it
- Why can this not be part of the `build_cmake.yml`

**Comment by albert-github** [comment]
Same questions with the [44f5ea6](https://github.com/doxygen/doxygen/pull/9914/commits/44f5ea6212bdcd403778f59d5ee5447e785c0386) update  as with the [13c9892](https://github.com/doxygen/doxygen/pull/9914/commits/13c9892ac6278e7b51df337ebf3af38c8c8ecab3) update.

**Comment by doxygen** [comment]
@ecxod `SameSite=Lax` is listed in the page to refer to, so why you say it is invalid? Does `SameSite=Strict` work cross browser with the same origin policy when the `file://` protocol is used?

**Comment by ecxod** [comment]
It's always the case that when you get to know people better, they disappoint you. Do what you want. i will compile a fork and work with my fork. To use a cookie for something you can do with CSS is already a hammer, But a question : is one frame in one domain (http://left.example.com) and the other in another domain (http:// right.example.com) ?

**Comment by doxygen** [comment]
> It's always the case that when you get to know people better, they disappoint you. 

Not sure what warrants such harsh reaction on a simple question.

> To use a cookie for something you can do with CSS is already a hammer, 

Care to explain?

> But a question : is one frame in one domain (http://left.example.com/) and the other in another domain (http:// right.example.com) ?

No, but doxygen's html pages are often viewed locally without web server, and one frame can be `file://some/path/file1.html` and another `file://some/path/file2.html` and then some browsers (such as Chrome) have the "same origin policy" implemented such that this is treated as two different domains.

**Comment by ecxod** [comment]
You don't need a cookie for this. If you don't like css, you can use localstorage or a session for such things. Cookies are only necesary if you want to comunicate between javascript and the server.

**Pull request closed without merging**
