### PR TITLE
issue #9192 "Packages" has a "Packages" in the tree

### PR DESCRIPTION
**Pull request by albert-github**
The problem here is the setting `OPTIMIZE_OUTPUT_JAVA   = YES, when  not having this setting we see "Namespaces" and "Namespace list" though for the "Package list" there is no translation function.
A function `trPackageList` has been introduced.

### CODE REVIEW

**Comment by albert-github** [comment]
- did you apply this proposed patch? As it is mot in master only in the branch of this patch.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> * did you apply this proposed patch? As it is mot in master only in the branch of this patch.

I tried. I followed the link to `albert-github:feature/issue_9192`  which is `https://github.com/albert-github/doxygen/tree/feature/issue_9192` and used the Clone-Repo URL there.
`https://github.com/albert-github/doxygen.git`

I have not checked that URL but it seems like it is wrong. I would call this a Bug on GitHub but MS is not interested in my use opinion. :D

So how do I clone explicit a branch/patch?

**Comment by albert-github** [comment]
I never have to do this for my own repository, but I gave it a try and I think the following steps are requited:
- `git clone https://github.com/albert-github/doxygen`
- `git checkout feature/issue_9192`

and now you can build the mentioned patch.

From the email I got for the proposed patch you might also try to apply, locally, the patch onto the current master:
-    https://github.com/doxygen/doxygen/pull/9197.patch
-    https://github.com/doxygen/doxygen/pull/9197.diff

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
OK, now it is working. The second `Packages` is now `Package List`. But why? :D
It still does not makes much sense for me.

Why not move the content under _Package List_ to _Packages_. Would make sense to me, save one click and one tree level?

Are there any situations where other entries appear under _Packages_ instead of _Package List_ and _Package Functions_?

And by the way (maybe a new Issue): Under _Package Functions_ there are more then just functions but also _Variables_.

**Comment by albert-github** [comment]
> Are there any situations where other entries appear under Packages instead of Package List and Package Functions?

By default no, but:
- for consistency with other tree items (like `Class`, `Interfaces` ....)
- the user can add add user defined sub item, e.g. `<tab type="user" url=".." title="..."/>`, see: https://www.doxygen.nl/manual/customize.html#layout)

> And by the way (maybe a new Issue): Under Package Functions there are more then just functions but also Variables.

When not using `OPTIMIZE_OUTPUT_JAVA   = YES` the displayed text is `Namespace Members` so the translation is probably not the best (as reference: the translator function is called: `trPackageMembers`)

**Comment by albert-github** [comment]
Regarding the remark about "Package Functions" I've just pushed a proposed patch, pull request #9206

**Comment by albert-github** [comment]
The pull request regarding the "Package Functions" (#9206) has been integrated in master on GitHub

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I would say we can merge this PR now.

**Pull request merged**
