### PR TITLE
doc: generate Doxygen's documentation.

### PR DESCRIPTION
**Pull request by groleo**
Add a sepparate project for Doxygen's documentation.
On Linux, you can build it with:

 mkdir doc/build/
 cd doc/build/
 cmake -Dbuild_doc=yes ..
 make docs

### CODE REVIEW

**Comment by albert-github** [comment]
I looked at the master branch as indicated with pull request #354. The comments are based on that version (but I don't expect major differences).

Thanks for the effort, some comments.
First a minor point I don't think on should not do the build in the doc directory directly, furthermore it should be part of the "general" configuration for doxygen.

I tried to run your master branch under Windows and Cygwin.

Cygwin (and similar under windows: Visual Studio 12 2013 and NMake Makefiles; all with build_doc=ON):
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.9.1")
CMake Error at doc/CMakeLists.txt:95 (file):
  file COPY cannot find
  "/cygdrive/d/Programs/Doxygen/groleo/doxygen/doc/config.doc".


CMake Error at doc/CMakeLists.txt:98 (file):
  file COPY cannot find
  "/cygdrive/d/Programs/Doxygen/groleo/doxygen/doc/../latex".


-- Looking for Q_WS_X11

I think there should not be a search for doxygen here but doxygen should be an internal dependency on the version build in the build environment (as it, as far as I know, done for the tests as well).

Just continued with -Dbuild_doc=OFF and than I tried to build according to the above recipe but I got:
CMake Error: The source directory "D:/Programs/Doxygen/groleo/doxygen/build_windows_nmake_v2013/doc" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

(When using the normal doc directory I'm expecting that I will get again the wrong doxygen version).

**Comment by groleo** [comment]
There are quite a few differences. Can you please try this pr ?
I've tested two scenarios on Linux:
1. build doxygen and docs in the same build/ directory.
2. build only docs, under doc/build/

**Comment by albert-github** [comment]
Tried to download the 357 but was a bit cumbersome, got not clone it
(probably my experience with git), so I cloned the master doxygen and
applied the patches on it.

First test with Cygwin again showed the problem regarding the wrong doxygen
version (not the generated one) and the missing files.
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.9.1")
CMake Error at doc/CMakeLists.txt:95 (file):
  file COPY cannot find
  "/cygdrive/d/Programs/Doxygen/groleo/doxygen/doc/config.doc".


CMake Error at doc/CMakeLists.txt:98 (file):
  file COPY cannot find
  "/cygdrive/d/Programs/Doxygen/groleo/doxygen/doc/../latex".

**Comment by groleo** [comment]
Thanks a lot for testing.
I'll give it a shot on Windows once I get home and fix it.

**Comment by groleo** [comment]
Erm, I found the issue : .gitignore again :)
I'll remove /latex and /html from it

**Comment by albert-github** [comment]
I removed the /html and /latex and all lines below it in .gitignore but problem remains.

**Comment by groleo** [comment]
Yea, they remain. I had the old latex dira in my build. My bad , sory

**Comment by groleo** [comment]
Fixed on windows_docs branch of my fork.
#357 should also contain the same code

**Comment by albert-github** [comment]
Sorry, still seeing 2 problems:
-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.9.1")
CMake Error at doc/CMakeLists.txt:94 (file):
  file COPY cannot find
  "/cygdrive/d/Programs/Doxygen/groleo/doxygen/doc/config.doc".

**Comment by groleo** [comment]
Fixed that one too.

**Comment by albert-github** [comment]
Next one?

-- Found Doxygen: /usr/bin/doxygen.exe (found version "1.8.9.1")
CMake Error at doc/CMakeLists.txt:91 (file):
  file COPY cannot find
  "/cygdrive/d/Programs/Doxygen/groleo/doxygen/doc/mailto.txt".

(only .gitignore and doc/CMakeLists.txt changed?).

Please look also at the wrongly used doxygen executable from /usr/bin/doxygen.exe

**Comment by groleo** [comment]
Yes. The .gitignore hides a lot of files that were generated in-tree.

**Comment by groleo** [comment]
The "doxygen.exe" issue is indeed a bit tricky. I have to see how i can
tell find_package to see if doxygen was built in tree. If not, search it on the system.

**Comment by albert-github** [comment]
I think that the doxygen executable has to come from the tree as the documentation is part of the build process and should not rely on a doxygen version that is installed on the system. In case a doxygen version is used from the system the documentation cannot contain new features that are in the development / the to be released version .

**Comment by albert-github** [comment]
Cygwin and nmake (v2013) versions went through.

Visual Studio version (v2013) gave an error:
2>CUSTOMBUILD : ! LaTeX error : There's no line here to end.
2>  
2>  See the LaTeX manual or LaTeX Companion for explanation.
2>  Type  H <return>  for immediate help.
2>   ...                                              
2>                                                    
2>  l.74 Manual for version $VERSION\\
2>                                    [2ex]
2>  ? 
2>  ! Emergency stop.
2>   ...                                              
2>                                                    
2>  l.74 Manual for version $VERSION\\
2>                                    [2ex]
2>  !  ==> Fatal error occurred, no output PDF file produced!

Looks like the $VERSION is not substituted in doxygen_manual.tex. It looks like that the Makefile is used and not make.bat as this file still contains the refman references (and I think this was also a / the major point for my initial version in pull request 354).

**Comment by groleo** [comment]
On Jun 17, 2015 8:25 PM, "albert-github" <notifications@github.com> wrote:
>
> Cygwin and nmake (v2013) versions went through.
>
> Visual Studio version (v2013) gave an error:
> 2>CUSTOMBUILD : ! LaTeX error : There's no line here to end.
> 2>
>
> 2> See the LaTeX manual or LaTeX Companion for explanation.
> 2> Type H for immediate help.
> 2> ...
>
> 2>
>
> 2> l.74 Manual for version $VERSION\
> 2> [2ex]
> 2> ?
> 2> ! Emergency stop.
> 2> ...
>
> 2>
>
> 2> l.74 Manual for version $VERSION\
> 2> [2ex]
> 2> ! ==> Fatal error occurred, no output PDF file produced!
>
> Looks like the $VERSION is not
It's because of how $VERSION and $$VERSION are expanded in the generated
buildfiles.
For makefiles, $$var is valid.
I'll use configure_file instead of that sed

substituted in doxygen_manual.tex. It looks like that the Makefile is used
and not make.bat as this file still contains the refman references (and I
think this was also a / the major point for my initial version in pull
request 354).

**Comment by groleo** [comment]
In 55216e2, SED was replaced with configure_file, so it should work on both VS and nmake

**Comment by albert-github** [comment]
Downloaded the zip file with the mentioned tag.

VS version:
=========
1>------ Build started: Project: doxygen_pdf, Configuration: Debug Win32 ------
1>  Building Custom Rule D:/Programs/Doxygen/groleo/55/doxygen-55216e26fd5550fac3bd25a2e118849055a75e45/doc/CMakeLists.txt
1>  CMake does not need to re-run because D:\Programs\Doxygen\groleo\55\doxygen-55216e26fd5550fac3bd25a2e118849055a75e45\build_windows_v2013\doc\CMakeFiles\generate.stamp is up-to-date.
1>  Generating Doxygen Manual PDF.
1>  The system cannot find the path specified.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1.
2>------ Build started: Project: docs, Configuration: Debug Win32 ------
2>  Building Custom Rule D:/Programs/Doxygen/groleo/55/doxygen-55216e26fd5550fac3bd25a2e118849055a75e45/doc/CMakeLists.txt
2>  CMake does not need to re-run because D:\Programs\Doxygen\groleo\55\doxygen-55216e26fd5550fac3bd25a2e118849055a75e45\build_windows_v2013\doc\CMakeFiles\generate.stamp is up-to-date.
2>  Error copying file "D:/Programs/Doxygen/groleo/55/doxygen-55216e26fd5550fac3bd25a2e118849055a75e45/doc/doxygen_logo.gif" to "html/".
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1.
========== Build: 0 succeeded, 2 failed, 1 up-to-date, 0 skipped ==========


Cygwin Version:
============
User-PC:/cygdrive/d/Programs/Doxygen/groleo/55/doxygen-55216e26fd5550fac3bd25a2e118849055a75e45/build_cygwin$ make docs
[100%] Generating Doxygen Manual PDF.
/bin/sh: line 0: cd: /cygdrive/d/Programs/Doxygen/groleo/55/doxygen-55216e26fd5550fac3bd25a2e118849055a75e45/build_cygwin/doc/latex: No such file or directory
doc/CMakeFiles/doxygen_pdf.dir/build.make:49: recipe for target 'doc/CMakeFiles/doxygen_pdf' failed
make[3]: *** [doc/CMakeFiles/doxygen_pdf] Error 1
CMakeFiles/Makefile2:432: recipe for target 'doc/CMakeFiles/doxygen_pdf.dir/all' failed
make[2]: *** [doc/CMakeFiles/doxygen_pdf.dir/all] Error 2
CMakeFiles/Makefile2:409: recipe for target 'doc/CMakeFiles/docs.dir/rule' failed
make[1]: *** [doc/CMakeFiles/docs.dir/rule] Error 2
Makefile:252: recipe for target 'docs' failed
make: *** [docs] Error 2

Nmake version:
============
D:\Programs\Doxygen\groleo\55\doxygen-55216e26fd5550fac3bd25a2e118849055a75e45\build_windows_nmake_v2013>nmake docs

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target doxygen_pdf
[100%] Generating Doxygen Manual PDF.
NMAKE : fatal error U1077: 'cd' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

Strange for me is that it looks like it starts with the buil dof the latex version, no HTML version build.

**Comment by groleo** [comment]
I managed to get a windows up and running.
Tested with nmake/vs2013.
It should also pick up the doxygen built, but you have to do it in two steps, so find_program gets
a chance to find doxygen.exe :
1. build doxygen (cmake ..)
2. generate docs (cmake -Dbuild_doc=yes ..)

**Comment by albert-github** [comment]
Did a quick test with nmake and this does build.
I still have problems with the 2 stage process for generating the documentation (the 2 stage process does work), as for the tests the tests are configured straight away to use the right executable (or is this possible due to the fact that the tests are not a separate configurable cmake target? in the later case it might be worthwhile if the docs would be handled in the same way).

**Comment by groleo** [comment]
I've rebased this as #358

**Pull request closed without merging**
