### PR TITLE
Reduce Qt-dependencies in dot-code and completely remove QThread & Co

### PR DESCRIPTION
**Pull request by cmorty**
There is still work to do to get at least the dot-code modernized (for-each, smart pointers) and QT-free, but this is a first step. I managed to remove QThread, QMutex and  QWaitCondition from the code, reducing the code size by over 1.5KLOC.
Although I tested this with a large project, maybe someone should tested on a few others before merging.

### CODE REVIEW

**Comment by cmorty** [comment]
....seems like https://miktex.org  is down. :(

**Comment by albert-github** [comment]
miktex.org is back online.

**Comment by cmorty** [comment]
@albert-github: Could you restart the build-job. I don't have the rights to do so.

**Comment by albert-github** [comment]
Unfortunately I cannot never figured out how to do it / having the rights for it.
A new commit / changed commit to this pull request will trigger a build though.

**Comment by cmorty** [comment]
Hmm. Seems like AppVeyor is happy, but did not report back.

**Comment by doxygen** [comment]
@cmorty Nice work! Thanks for helping out to modernize doxygen!

**Comment by cmorty** [comment]
@doxygen Thanks. There are some patches in the pipeline. I'm quite often struggling whether it's worth changing `Q(C)string` to `std::string` as `std::filesystem` only arrives in C++17. If moving to C++17 is an option that might help getting the dot-code QT-free. ;)

**Pull request merged**
