### PR TITLE
issue #6950 XML - <initializer> for array of structure only contains references in first array element

### PR DESCRIPTION
**Pull request by albert-github**
Don't stop at a hexadecimal number, but output the hexadecimal number (plus the part that has not been printed yet) and continue with the next input part.

### CODE REVIEW

**Comment by albert-github** [comment]
The given solution is a general solution applying also for other places.
For the specific problem the change in routine `static void generateXMLForMember(const MemberDef *md,FTextStream &ti,FTextStream...` of `xmlgen.cpp` from:
```
     t << "        <initializer>";
     linkifyText(TextGeneratorXMLImpl(t),def,md->getBodyDef(),md,md->initializer());
     t << "</initializer>" << endl;
```
into
```
   t << "        <initializer>";
   SrcLangExt lang = md->getLanguage();
   ParserInterface *pIntf = Doxygen::parserManager->getParser(md->getDefFileExtension());
   pIntf->resetCodeParserState();
   XMLCodeGenerator *xmlGen = new XMLCodeGenerator(t);
   pIntf->parseCode(*xmlGen,0,md->initializer(),lang,FALSE,0,const_cast<FileDef*>(md->getFileDef()),
                    -1,-1,TRUE,md,FALSE,md);
   xmlGen->finish();
   delete xmlGen;
   t << "</initializer>" << endl;
```
would probably more consistent with the other output generators (xml has its own output generator separated from, most, other generators), but would introduce extra tags in the `<initializer>` part like:
`<codeline>`, `<highlight class="normal">`, <sp/>i and thus being inconsistent with the current situation. Also output of the standard test would have to be slightly adjusted with these extra tags.

**Comment by krausedj** [comment]
I pulled and built this, and it is working in my use case.  I think I understand the change as described.

I know I am only an outsider, but your secondary comment about using parseCode, does look more aligned with the other generators.

**Comment by doxygen** [comment]
@albert-github  Removed the redundant (?) line before the while loop, and made some simplications. See https://github.com/doxygen/doxygen/commit/b8ed98e5b9e84f70bbe485094320201caf1f1ecb

**Comment by albert-github** [comment]
@doxygen 
Statement looks indeed redundant.

**Pull request merged**
