### PR TITLE
add enum type in PERLMOD

### PR DESCRIPTION
**Pull request by cheoljoo**
- we can see the followin enum in c++.
- but , we could not find enum type in perlmod. so I add enum type

```cpp
enum class Handle : std::uint32_t { Invalid = 0 };
```

- DoxyDocs.pm in OUTPUT/perlmod - add the enum type like ```type => 'std::uint32_t',```

### CODE REVIEW

**Comment by albert-github** [comment]
I see in `perlmodgen.cpp` around line 1768: `   if (md->memberType()==MemberType_Enumeration) // enum`.
Wouldn't it be better to have it around this place / as part of this definition? Maybe also some reference to the fact that it is an `enum class` so a "strong" enum might be good to have.

**Comment by cheoljoo** [comment]
Dear @albert-github.
- I change the code place according to your advice.
- please review again.  thanks

**Comment by cheoljoo** [comment]
Dear @albert-github 
I have the question for "Quality Gate Failed".
This failure is not related to my contribution.
Do I change them to pass this process?

With BestRegards. ~Charles

**Comment by albert-github** [comment]
As they are not related to your code please ignore them.

**Comment by cheoljoo** [comment]
Dear @albert-github 
At the first time , we have several issue in Quality Gate.
2 issues are solved. 
last issue is [13.3% Duplication on New Code](https://sonarcloud.io/component_measures?id=doxygen_doxygen&pullRequest=10554&metric=new_duplicated_lines_density&view=list) (required ≤ 3%).
but I added only one line. Could you give your advice how to solve 13.3% duplication issue?

Thanks in advance. ~Charles

**Comment by albert-github** [comment]
Looks like they are not related to your code please ignore them.

**Pull request merged**
