### PR TITLE
Implement search by each significant word from page caption

### PR DESCRIPTION
**Pull request by apolukhin**
This patch does the following:
* Makes the `g_searchIndexInfo` value store `lowercase(searchName) -> definitions relations` rather than `lowercase(searchName[0]) -> definitions relations`
* When the JL index is being formed, the `g_searchIndexInfo` is mapped to `searchName[0]` to repeat the old logic
* `splitSearchTokens` splits the titles into multiple words and adds each word into `g_searchIndexInfo`
* `writeJavasScriptSearchDataPage` now iterates over `search id`, that simplifies the function logic

Addresses https://github.com/doxygen/doxygen/issues/4111

### CODE REVIEW

**Comment by apolukhin** [comment]
> looks like a lowercase conversion is gone?

It is now in the `SearchIndexInfo::add` function. Investigating the crash

**Comment by apolukhin** [comment]
Found and fixed some issue with multithreaded runs. Still testing the fix. Meanwhile, I'm open to any requests/sugestions/comments/...

**Comment by apolukhin** [comment]
`make docs_internal` finished well with the fix:

image

Our docs were also built well:

image_2023-08-07_20-39-01

**Comment by albert-github** [comment]
Did a few other tests on the doxygen internal documentation/ When searching for `intern` we get:
image

note the `%` sign (which is present to prevent linking to the `Doxygen` class).
Searching for `doxygen` / `Doxygen` didn't give a result (regarding this header).
Searching for `%` gave
image
but this was also the case in the doxygen versions before the changes.

@doxygen
- shouldn't actually the results of the % search be omitted?
- shouldn't the results in the search panel be "filtered"?

I created a small project where I also experimented a bit with the html entities (`&...;`) and in the search panel also the html entities are shown (search for `load`): [example.tar.gz](https://github.com/doxygen/doxygen/files/12289328/example.tar.gz)

**Comment by albert-github** [comment]
Looks like I found another problem.

When searching for `%doxygen in` before the changes I got:
image

and after the changes I get:
image

Here it is not so spectacular, but when searching for e.g. `overview of` it is even clearer.



I see also a positive change (at least the one that I found):
Old:
image

New:
image

where the `number` are merged

**Comment by apolukhin** [comment]
Fixed search by multiple words in 45d2a9c08e64942419a9834e769042e3bcd47e60. Here's a playground if someone needs one https://userver.tech/

The `%` searches I'd rather fix in a separate PR later. IMO this one is quite big already

**Comment by albert-github** [comment]
You wrote:
> IMO this one is quite big already

it is not that big, e.g. https://github.com/doxygen/doxygen/pull/9825 is bigger.


I'm not totally getting the:
> The % searches I'd rather fix in a separate PR later.

I see already a number of fixes regarding the `%` or did you mean the `%` in the search panel (with this I would agree as it is a more separate issue, and would probably also solve issues with the html entities `&...;`)

**Comment by apolukhin** [comment]
> I see already a number of fixes regarding the `% or` did you mean the % in the search panel

Yes, I've experimented with `%` but removed all the `%` related code for now.

I could restore the `%` related changes if the following behavior is fine:
* the `%doxygen` search would stop working, only 'doxygen'* wold do the job. The search result would still contain the `%Doxygen internals`
* for the title `some1 %some2`
  * the `some1 some2` search would work
  * the `some1 %some2` search *not* work

**Comment by albert-github** [comment]
I think that goal should be that entering in the search box the text as seen on the pages it will show up. That, temporarily, the e.g. `%` is shown in the search results is not nice, but this happens now as well and can be handled later.

All in all it remains a difficult topic.

**Comment by apolukhin** [comment]
Seems that I've fixed the `%` issue:

image

`%` in the title is kept if it does not followed by word. For `\page pg_cmds_int Overview % of introduction of internal special commands` doxygen still generates:

image

**Comment by apolukhin** [comment]
The `macOS Latest Release` CI run failed because of some network issue

**Comment by apolukhin** [comment]
CI passed well.

Is there anything I can do to speedup the review process and to get this PR merged for the next release of doxygen?

**Comment by apolukhin** [comment]
Something wrong with certificates in MacOS CI. The other tests pass well

**Comment by doxygen** [comment]
@apolukhin I decided to add section titles as well and did some performance improvements/restructuring (i.e. directly store the results in the right format so `getSearchIndexMapByLetter` is no longer needed and optimize the `splitSearchTokens` function. See https://github.com/doxygen/doxygen/commit/42391fce4676eeffc64f5836c66db359355fe61b and check if I didn't accidentally break something that was working in the changes you made.

**Comment by apolukhin** [comment]
Looks great!

Noted a small typo the prevents searching for a word after some special chars. See https://github.com/doxygen/doxygen/pull/10243

**Pull request merged**
