### PR TITLE
issue #11273 Using a tilde in the URL of a Markdown image tag breaks the tag if the image is in the IMAGE_PATH

### PR DESCRIPTION
**Pull request by albert-github**
Adding possibility to use a `~` in the file / directory name except on the first position of a file / directory name

### CODE REVIEW

**Comment by doxygen** [comment]
@albert-github I've tested on my Mac if I can also create an `~Example` directory with the test image file inside and that also seems to work fine! The directory appears as `'~Example'` when I list it (so with quotes around it), but can be accessed by doxygen without problems. This would mean that all the REJECT statements can be removed.

**Comment by albert-github** [comment]
@doxygen 
That would make everything quite a bit simpler.
Did you test it on the Mac with or without the `REJECT` statements in place?

Should I change the PR or will you do it?

**Comment by doxygen** [comment]
@albert-github I tested without the rejects (with the reject the image is completely ignored). I'll change it.

**Comment by albert-github** [comment]
OK.

> with the reject the image is completely ignored

That was the intention of my changes, to keep it consistent with the old version when the `~` was at the first place and only allow a `~` at the second and following places, but as your tests reveal that at the first place it works as well it is good to allow it as well (less exceptions).
I assume there is no user `Example` on your Mac, what happens when you use a file at `~User` where `User` is a user of the system?

**Comment by doxygen** [comment]
> I assume there is no user Example on your Mac, what happens when you use a file at ~User where User is a user of the system?

I just tested with user `~dimitri` as well (which does exist on my Mac). Also works. I guess the ~name is only something interpreted by the shell, not something special in the filesystem or the functions that work on the filesystem like `fopen()`.

**Comment by albert-github** [comment]
Most likely / probably the `deps/filesystem` takes care of it.
It might give differences between *nix systems and Windows as on windows the `~` concept is not known (but it will hardly be the case that a user will reference to his home directory, will most likely be bad practice).

**Pull request merged**
