### PR TITLE
fixed bug of .dot files being deleted to early or processed multiple times

### PR DESCRIPTION
**Pull request by thomas-haller**
issue #6960

in some cases dot is still called although not needed. But this is only a performance issue not a real bug.

### CODE REVIEW

**Comment by albert-github** [comment]
Some thoughts about the patch.

I think it might work, though it looks at the end if a file already exists
- I think this is a bit late
- The question is also is it guaranteed the the contents is the same (except for the node numbers)


In the past the nodes were numbered per file / graph, but due to some problems with uniqueness this has been changed, so here a case of not the same files, probably, went unnoticed.
So the basic questions are:
- why is the file generated twice, can we prevent this
- is it possible that the files are not identical (except for the node numbers), in this case doxygen would have a bit a bigger problem.

**Comment by thomas-haller** [comment]
You are right. This patch is more a damage limitation, because it is still possible that a file is regenerated which does not need a regeneration.

The first bug is that the file is generated (twice or more often) although not needed. This currently happens due to the node numbers changing. Do you think it is possible to renumber just inside the .dot file relative to the first node? So the first node becomes '0' and all others change their value relative to it?

I did not observe that not identical files are generated, but we could add a test for that. Just check if the file is queued for regeneration if the md5 do not match. That should not happen.

The second bug is that the .dot file becomes deleted while the file is queued for regeneration. This also has the side effect that in the html code the text for not-regenerated files is inserted. For this bug I think my patch is a good solution.

**Comment by albert-github** [comment]
No, I don't think it would be OK to renumber the nodes. The numbering has been chosen so when having multiple images (with map files etc.) in one output file it won't be possible that there is more than one time a certain label.

I did not observe the problem of one file name with different content (excluding the different node numbers of course), but I'm not 100% sure it cannot happen.

A strategy that I could think of is that the md5 sum is not calculated over the complete image but over the "stripped" image where 'Node[0-9]*' is replaced by 'Node' so the structure is checked.

**Comment by thomas-haller** [comment]
I am currently writing more improvements in dot.cpp and I am not sure if it is a good idea to remove the node numbers for md5. I can think of some cases in which the node numbers can partly change and produce a different output (which should have a different md5).

Can you explain in more detail why it is not possible to renumber the nodes inside the .dot files? I only found this line which says the node numbers are ignored.
https://github.com/doxygen/doxygen/blob/2840a9aede8fd841d8e0602f8f093665681d4fc7/src/dot.cpp#L398

**Comment by albert-github** [comment]
I have in the back of my head that there otherwise would be a problem with xhtml, but at the moment I don't have prove / a case for it.
In case the id="..." is always striped out of the map part but I'm not 100% sure what happens in other parts of the output.
The case "in which the node numbers can partly change and produce a different output (which should have a different md5)." would be "disastrous" when this is possible as we have at that moment exactly the case with different images but with one filename!

**Comment by cmorty** [comment]
@albert-github . It's important the the `<map>` tag's ID is correct, as that gets referenced. However the actual node ids shouldn't matter. They get removed from the map file and for producing a png they don't matter at all.
And as you said yourself: In case they would matter there would already be lots of issues.

**Comment by albert-github** [comment]
Closed as obsolete due to implementation of alternate solution (#6987).

**Pull request closed without merging**
