### PR TITLE
Ignore c11 static assert

### PR DESCRIPTION
**Pull request by sebhub**

### CODE REVIEW

**Comment by sebhub** [comment]
> Shouldn't the "_Static_assert" also be mentioned in the function `skipLanguageSpecificKeyword` in code.l (around line 3798)?

The test case did pass without adding `_Static_assert` to `skipLanguageSpecificKeyword`. I don't know the code good enough to judge if this is necessary. If I run the test case in GDB and set a break point to skipLanguageSpecificKeyword() it is not hit. What do I have to do so that this function is called?

**Comment by albert-github** [comment]
In the `skipLanguageSpecificKeyword ` function we see:
```
...
    case SrcLangExt_Java:
      retval = (non_java_keywords.find(keyword) != non_java_keywords.end());
      break;
...
```

so it is hit in case we have java code.

**Comment by sebhub** [comment]
Ok, but Java has no _Static_assert keyword. This keyword is specific to C11. In C23 it it was deprecated, however, Doxygen should still ignore it.

**Comment by albert-github** [comment]
The variable is `non_java_keywords` so as java doesn't have this keyword I think it should be added in this list.

**Comment by sebhub** [comment]
Ok, now I understand. I will try to improve the test case and update the pull request.

**Comment by sebhub** [comment]
Thanks for pointing out the bug in my fix. I added a test case which shows that skipLanguageSpecificKeyword() definitely needs the suggested update.

**Pull request merged**
