### PR TITLE
cmake: Fix flex version check for overriding the register keyword

### PR DESCRIPTION
**Pull request by lazka**
In #11113 a check was added to override the "register" keyword for older versions of flex. The check was added before the find_package() call which resulted in the workaround being active for any version of flex. This breaks the build with recent mingw-w64 which uses "register" in its headers.

Fix by moving the version check after the find_package() call.

### CODE REVIEW

**Comment by lazka** [comment]
@albert-github

**Comment by albert-github** [comment]
@lazka 
- What kind of error messages do you get?
- Which version of cmake and flex are you using
- What is the output of your initial cmake run (the configuration run).

**Comment by lazka** [comment]
> * What kind of error messages do you get?

https://sourceforge.net/p/mingw-w64/mailman/message/59112743/

> * Which version of cmake and flex are you using

```console
$ cmake --version
cmake version 3.31.3
$ flex --version
flex 2.6.4
```

> * What is the output of your initial cmake run (the configuration run).

```console
$ cmake . -Wno-dev
-- Building for: Ninja
-- The C compiler identification is Clang 19.1.6
-- The CXX compiler identification is Clang 19.1.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/clang64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/clang64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Cmake version 3.31.3
-- Found Python: C:/Python312/python.exe (found version "3.12.7") found components: Interpreter
-- Found FLEX: C:/msys64/usr/bin/flex.exe (found version "2.6.4")
-- Found BISON: C:/msys64/usr/bin/bison.exe (found version "3.8.2")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Iconv: C:/msys64/clang64/lib/libiconv.dll.a (found version "1.18")
-- Build spdlog: 1.14.1
-- Build type: Release
-- The javacc executable not found, using existing files
-- The generateDS executable not found, using existing files
-- Configuring done (3.2s)
-- Generating done (0.1s)
-- Build files have been written to: C:/msys64/home/user/git/doxygen
```

**Comment by albert-github** [comment]
The test indeed looks like to be at the completely wrong place.

**Comment by lazka** [comment]
Thank you!

**Pull request merged**
